import type { WidgetDefinition, WidgetKind } from "./types";

function definition(
  name: string,
  category: string,
  description: string,
  width: number,
  height: number,
  title: string,
  subtitle = "",
  value = "",
  items = "",
): Omit<WidgetDefinition, "kind"> {
  return {
    name,
    category,
    description,
    width,
    height,
    title,
    subtitle,
    value,
    items,
  };
}

// A record makes adding a WidgetKind a compile-time obligation here.
const definitions: Record<WidgetKind, Omit<WidgetDefinition, "kind">> = {
  sidebar: definition(
    "Sidebar",
    "Navigation",
    "Workspace identity, logo and vertical navigation.",
    232,
    720,
    "Acme Studio",
    "Workspace / Pro",
    "AS",
    "Overview\nAnalytics\nProjects\nTeam\nSettings",
  ),
  navbar: definition(
    "Navigation bar",
    "Navigation",
    "Compact page navigation with a workspace identity.",
    920,
    80,
    "Overview",
    "Monday, September 7",
    "JD",
    "Dashboard\nReports\nSettings",
  ),
  heading: definition(
    "Heading",
    "Content",
    "Page title and supporting introduction.",
    600,
    112,
    "Workspace overview",
    "A little clarity for your next big move.",
  ),
  text: definition(
    "Text",
    "Content",
    "Readable body copy with preserved line breaks.",
    400,
    160,
    "Built for your next chapter",
    "Bring your team, projects, and ideas into one focused workspace.",
  ),
  stat: definition(
    "Statistic",
    "Data",
    "A headline metric with a supporting trend.",
    256,
    164,
    "Total revenue",
    "vs. previous month",
    "$48,250",
    "+12.8%",
  ),
  "line-chart": definition(
    "Line chart",
    "Data",
    "Deterministic SVG trend. Items use label | number.",
    520,
    300,
    "Revenue over time",
    "A steady rhythm of growth",
    "$48,250",
    "Jan | 24\nFeb | 38\nMar | 31\nApr | 54\nMay | 46\nJun | 72",
  ),
  "bar-chart": definition(
    "Bar chart",
    "Data",
    "Compare numeric values with accessible SVG bars.",
    420,
    300,
    "Weekly activity",
    "Completed tasks by day",
    "146",
    "Mon | 24\nTue | 38\nWed | 18\nThu | 42\nFri | 24",
  ),
  "donut-chart": definition(
    "Donut chart",
    "Data",
    "Part-to-whole chart with a readable legend.",
    340,
    320,
    "Traffic sources",
    "Where your audience finds you",
    "2,840",
    "Direct | 48\nSearch | 32\nReferral | 20",
  ),
  table: definition(
    "Data table",
    "Data",
    "First line supplies headers; separate cells with |.",
    660,
    320,
    "Recent transactions",
    "Your latest workspace activity",
    "View all",
    "Customer | Status | Amount\nOlivia Rhye | Paid | $420.00\nPhoenix Baker | Pending | $185.00\nLana Steiner | Paid | $640.00\nDemi Wilkinson | Paid | $290.00",
  ),
  activity: definition(
    "Activity feed",
    "Data",
    "Chronological updates. Items use event | detail.",
    380,
    340,
    "Team activity",
    "The latest from your workspace",
    "",
    "Olivia published a report | 2 minutes ago\nPhoenix joined the project | 28 minutes ago\nDesign review completed | 1 hour ago",
  ),
  card: definition(
    "Card",
    "Content",
    "A flexible content panel with a primary action.",
    340,
    240,
    "Make room for good work",
    "Everything your team needs to turn a promising idea into something real.",
    "Explore project",
    "Shared workspace\nThoughtful collaboration",
  ),
  button: definition(
    "Button",
    "Forms",
    "Native button with focus and disabled states.",
    184,
    72,
    "Create project",
  ),
  input: definition(
    "Text input",
    "Forms",
    "Labeled native text field and helper text.",
    340,
    116,
    "Project name",
    "Choose a name your team will recognize.",
    "Website redesign",
  ),
  textarea: definition(
    "Text area",
    "Forms",
    "Labeled multiline text entry.",
    380,
    196,
    "Project brief",
    "A few words about what you are building.",
    "Create a calmer, more useful workspace.",
  ),
  select: definition(
    "Select",
    "Forms",
    "Native accessible option picker.",
    300,
    116,
    "Project status",
    "Keep everyone on the same page.",
    "In progress",
    "Planning\nIn progress\nIn review\nComplete",
  ),
  checkbox: definition(
    "Checkbox",
    "Forms",
    "Native checkbox with a visible text label.",
    340,
    100,
    "Email updates",
    "Get a weekly summary of your workspace.",
    "true",
  ),
  switch: definition(
    "Switch",
    "Forms",
    "Native checkbox presented as an on/off switch.",
    340,
    100,
    "Notifications",
    "Stay in the loop with project updates.",
    "true",
  ),
  badge: definition(
    "Badge",
    "Content",
    "Compact status or category label.",
    160,
    64,
    "In progress",
  ),
  avatar: definition(
    "Avatar",
    "Content",
    "Uploaded portrait or initials with identity text.",
    280,
    100,
    "Jordan Davis",
    "Product designer",
    "JD",
  ),
  image: definition(
    "Image",
    "Content",
    "Uploaded raster or secure image with descriptive alt text.",
    440,
    280,
    "A fresh perspective",
    "Your image, your story.",
  ),
  progress: definition(
    "Progress",
    "Data",
    "Native progress meter; value is clamped to 0–100.",
    360,
    124,
    "Monthly target",
    "You are making great progress.",
    "72",
  ),
  alert: definition(
    "Alert",
    "Feedback",
    "Visible announcement with accessible alert semantics.",
    460,
    140,
    "Your workspace is up to date",
    "All changes have been saved successfully.",
    "Information",
  ),
  tabs: definition(
    "Tabs",
    "Navigation",
    "CSS-only native radio panels with keyboard selection.",
    460,
    220,
    "Project details",
    "Select a section to explore.",
    "",
    "Overview | Your project at a glance.\nActivity | Recent updates from the team.\nSettings | Workspace preferences.",
  ),
  accordion: definition(
    "Accordion",
    "Content",
    "Native expandable details; use question | answer.",
    460,
    280,
    "Frequently asked questions",
    "A few things you might want to know.",
    "",
    "How does it work? | Start with a project and invite your team.\nCan I change my plan? | You can update your plan at any time.\nWhere is my work saved? | This is an editable interface sample.",
  ),
  breadcrumb: definition(
    "Breadcrumb",
    "Navigation",
    "Ordered navigation trail.",
    400,
    72,
    "You are here",
    "",
    "",
    "Workspace\nProjects\nWebsite redesign",
  ),
  pagination: definition(
    "Pagination",
    "Navigation",
    "Page selection sample with the current page identified.",
    320,
    76,
    "Pages",
    "Page 1 of 5",
    "1",
    "1\n2\n3\n4\n5",
  ),
  divider: definition(
    "Divider",
    "Content",
    "A section separator with an optional label.",
    440,
    56,
    "Continue exploring",
  ),
  skeleton: definition(
    "Skeleton",
    "Feedback",
    "Animated placeholder with reduced-motion support.",
    360,
    180,
    "Loading content",
    "Just a moment.",
  ),
  pricing: definition(
    "Pricing card",
    "Commerce",
    "Plan price, features, and a call to action.",
    340,
    400,
    "Professional",
    "For teams with bigger ideas.",
    "$29",
    "Unlimited projects\nAdvanced analytics\nPriority support\nTeam collaboration",
  ),
  login: definition(
    "Sign-in form",
    "Forms",
    "Labeled email/password fields; no backend connection.",
    400,
    400,
    "Welcome back",
    "Sign in to your workspace.",
    "Sign in",
  ),
  search: definition(
    "Search",
    "Forms",
    "Native search input with visible labeling.",
    400,
    108,
    "Search workspace",
    "Find projects, people, and files.",
  ),
  chat: definition(
    "Chat messages",
    "Agentic",
    "Conversation sample. Items use speaker | message.",
    460,
    360,
    "Project assistant",
    "Conversation preview",
    "",
    "You | Summarize our progress this week.\nAssistant | Three milestones are complete. The design review is ready for your attention.\nYou | Great, show me the next steps.",
  ),
  composer: definition(
    "Message composer",
    "Agentic",
    "Editable message field and send button sample.",
    480,
    176,
    "Message assistant",
    "Describe what you would like to work on.",
    "Send message",
  ),
  agent: definition(
    "Agent status",
    "Agentic",
    "Visible execution summary without private reasoning.",
    360,
    240,
    "Research assistant",
    "Preparing your weekly summary",
    "Ready",
    "Collect sources\nOrganize findings\nPrepare summary",
  ),
  approval: definition(
    "Approval request",
    "Agentic",
    "Review a proposed action with explicit choice buttons.",
    440,
    260,
    "Review proposed action",
    "The assistant would like to publish the weekly report.",
    "Awaiting review",
    "Action | Publish report\nDestination | Team workspace",
  ),
  file: definition(
    "File attachment",
    "Agentic",
    "File identity and metadata sample.",
    340,
    120,
    "quarterly-report.pdf",
    "2.4 MB · PDF document",
    "PDF",
  ),
  calendar: definition(
    "Calendar",
    "Data",
    "Deterministic month sample with a selected day.",
    360,
    360,
    "September 2026",
    "Project schedule",
    "7",
    "7 | Design review\n14 | Team planning\n25 | Launch day",
  ),
  list: definition(
    "List",
    "Content",
    "Structured list. Items use title | description.",
    360,
    260,
    "Your priorities",
    "Make space for what matters.",
    "",
    "Review designs | Website refresh\nShare feedback | Team workspace\nPlan next week | Product roadmap",
  ),
  kanban: definition(
    "Kanban board",
    "Agentic",
    "Sample task columns. Items use column | task.",
    760,
    340,
    "Project board",
    "A clear view of work in motion.",
    "",
    "To do | Write project brief\nTo do | Collect references\nIn progress | Design dashboard\nIn review | Review typography\nDone | Set up workspace",
  ),
  tooltip: definition(
    "Tooltip",
    "Feedback",
    "Keyboard-accessible disclosure with helper information.",
    300,
    144,
    "A little more context",
    "This information helps you make a more informed choice.",
    "Learn more",
  ),
};

export const widgetCatalog: WidgetDefinition[] = (
  Object.keys(definitions) as WidgetKind[]
).map((kind) => ({ kind, ...definitions[kind] }));
