import type { DesignPreset } from "./types";

// Derived token data: VoltAgent/awesome-design-md, MIT.
// See THIRD_PARTY_NOTICES.md for the pinned revision and complete license.
// Each source folder has one preset; Nimbus is the original, first entry.
// Font categories use system fonts. Translucent borders are flattened to hex.
// These are independent interpretations, not official company design systems.
export const designPresets: DesignPreset[] = [
  {
    id: "nimbus",
    name: "Nimbus",
    description:
      "Clean white surfaces with indigo accents for everyday studio work.",
    category: "Core",
    source: "",
    style: {
      background: "#ffffff",
      color: "#24272e",
      accent: "#6366f1",
      borderColor: "#e5e7eb",
      radius: 8,
      borderWidth: 1,
      padding: 20,
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "airbnb",
    name: "Airbnb",
    description:
      "Airbnb inspired: White surfaces, coral accents, and softly rounded cards.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/airbnb/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#222222",
      accent: "#ff385c",
      borderColor: "#dddddd",
      radius: 14,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "small",
      opacity: 100,
    },
  },
  {
    id: "airtable",
    name: "Airtable",
    description:
      "Airtable inspired: Clear white panels with dark ink and generous card spacing.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/airtable/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#181d26",
      accent: "#181d26",
      borderColor: "#dddddd",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "apple",
    name: "Apple",
    description:
      "Apple inspired: White space, blue actions, and quiet rounded surfaces.",
    category: "Hardware",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/apple/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#1d1d1f",
      accent: "#0066cc",
      borderColor: "#e0e0e0",
      radius: 18,
      borderWidth: 1,
      padding: 24,
      fontSize: 17,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "binance",
    name: "Binance",
    description:
      "Binance inspired: Deep charcoal surfaces with yellow actions and compact type.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/binance/DESIGN.md",
    style: {
      background: "#0b0e11",
      color: "#eaecef",
      accent: "#fcd535",
      borderColor: "#2b3139",
      radius: 8,
      borderWidth: 1,
      padding: 24,
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "bmw",
    name: "BMW",
    description:
      "BMW inspired: White surfaces, blue accents, and light body type.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/bmw/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#262626",
      accent: "#1c69d4",
      borderColor: "#e6e6e6",
      radius: 4,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 300,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "bmw-m",
    name: "BMW M",
    description:
      "BMW M inspired: Black surfaces, light typography, and crisp corners.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/bmw-m/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#ffffff",
      borderColor: "#3c3c3c",
      radius: 0,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 300,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "bugatti",
    name: "Bugatti",
    description:
      "Bugatti inspired: Black and white with serif text and square edges.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/bugatti/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#ffffff",
      borderColor: "#262626",
      radius: 0,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "serif",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "cal",
    name: "Cal.com",
    description:
      "Cal.com inspired: Monochrome scheduling panels with soft card corners.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/cal/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#111111",
      accent: "#111111",
      borderColor: "#e5e7eb",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "claude",
    name: "Anthropic Claude",
    description:
      "Anthropic Claude inspired: Warm cream, coral accents, and an editorial serif voice.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/claude/DESIGN.md",
    style: {
      background: "#faf9f5",
      color: "#141413",
      accent: "#cc785c",
      borderColor: "#e6dfd8",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "serif",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "clay",
    name: "Clay",
    description:
      "Clay inspired: Cream surfaces, pink accents, and generous rounded cards.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/clay/DESIGN.md",
    style: {
      background: "#fffaf0",
      color: "#0a0a0a",
      accent: "#ff4d8b",
      borderColor: "#e5e5e5",
      radius: 24,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    description:
      "ClickHouse inspired: Near-black panels with electric yellow accents.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/clickhouse/DESIGN.md",
    style: {
      background: "#0a0a0a",
      color: "#ffffff",
      accent: "#faff69",
      borderColor: "#2a2a2a",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "cohere",
    name: "Cohere",
    description:
      "Cohere inspired: White editorial surfaces with deep green accents.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/cohere/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#212121",
      accent: "#003c33",
      borderColor: "#d9d9dd",
      radius: 22,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "coinbase",
    name: "Coinbase",
    description:
      "Coinbase inspired: White panels, vivid blue actions, and spacious rounded cards.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/coinbase/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#0a0b0d",
      accent: "#0052ff",
      borderColor: "#dee1e6",
      radius: 24,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "composio",
    name: "Composio",
    description:
      "Composio inspired: Dark technical panels with a concentrated blue accent.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/composio/DESIGN.md",
    style: {
      background: "#0f0f0f",
      color: "#ffffff",
      accent: "#0007cd",
      borderColor: "#222222",
      radius: 16,
      borderWidth: 1,
      padding: 28,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "cursor",
    name: "Cursor",
    description:
      "Cursor inspired: Warm off-white, orange accents, and restrained hairlines.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/cursor/DESIGN.md",
    style: {
      background: "#f7f7f4",
      color: "#26251e",
      accent: "#f54e00",
      borderColor: "#e6e5e0",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "dell-1996",
    name: "Dell (1996)",
    description:
      "Dell (1996) inspired: Retro white panels with serif text, red accents, and square borders.",
    category: "Hardware",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/dell-1996/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#e91d2a",
      borderColor: "#000000",
      radius: 0,
      borderWidth: 1,
      padding: 16,
      fontSize: 14,
      fontFamily: "serif",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description:
      "ElevenLabs inspired: Soft off-white with warm dark ink and rounded cards.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/elevenlabs/DESIGN.md",
    style: {
      background: "#f5f5f5",
      color: "#0c0a09",
      accent: "#292524",
      borderColor: "#e7e5e4",
      radius: 16,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "expo",
    name: "Expo",
    description:
      "Expo inspired: White developer panels with black actions and light dividers.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/expo/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#171717",
      accent: "#000000",
      borderColor: "#f0f0f3",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "ferrari",
    name: "Ferrari",
    description:
      "Ferrari inspired: Dark surfaces, racing-red accents, and angular edges.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/ferrari/DESIGN.md",
    style: {
      background: "#181818",
      color: "#ffffff",
      accent: "#da291c",
      borderColor: "#303030",
      radius: 0,
      borderWidth: 0,
      padding: 24,
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "figma",
    name: "Figma",
    description:
      "Figma inspired: White panels, black actions, and generous rounded geometry.",
    category: "Design tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/figma/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#000000",
      borderColor: "#e6e6e6",
      radius: 24,
      borderWidth: 1,
      padding: 24,
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 320,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "framer",
    name: "Framer",
    description:
      "Framer inspired: Dark artboard surfaces with blue accents and rounded panels.",
    category: "Design tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/framer/DESIGN.md",
    style: {
      background: "#090909",
      color: "#ffffff",
      accent: "#0099ff",
      borderColor: "#262626",
      radius: 20,
      borderWidth: 1,
      padding: 24,
      fontSize: 15,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "hashicorp",
    name: "HashiCorp",
    description:
      "HashiCorp inspired: Black infrastructure panels with blue accents and medium-weight text.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/hashicorp/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#2b89ff",
      borderColor: "#3b3d45",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 500,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "hp",
    name: "HP",
    description:
      "HP inspired: White product panels with electric blue and rounded corners.",
    category: "Hardware",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/hp/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#1a1a1a",
      accent: "#024ad8",
      borderColor: "#e8e8e8",
      radius: 16,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "ibm",
    name: "IBM",
    description:
      "IBM inspired: Flat white tiles, assertive blue, and square corners.",
    category: "Enterprise",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/ibm/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#161616",
      accent: "#0f62fe",
      borderColor: "#e0e0e0",
      radius: 0,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "intercom",
    name: "Intercom",
    description:
      "Intercom inspired: Warm cream panels with orange accents and light borders.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/intercom/DESIGN.md",
    style: {
      background: "#f5f1ec",
      color: "#111111",
      accent: "#ff5600",
      borderColor: "#d3cec6",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "kraken",
    name: "Kraken",
    description:
      "Kraken inspired: White surfaces, vivid purple, and gentle rounded edges.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/kraken/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#101114",
      accent: "#7132f5",
      borderColor: "#dedee5",
      radius: 12,
      borderWidth: 1,
      padding: 16,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "small",
      opacity: 100,
    },
  },
  {
    id: "lamborghini",
    name: "Lamborghini",
    description:
      "Lamborghini inspired: Black surfaces with gold accents and square geometry.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/lamborghini/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#ffc000",
      borderColor: "#313131",
      radius: 0,
      borderWidth: 0,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "linear.app",
    name: "Linear",
    description:
      "Linear inspired: Near-black panels, lavender-blue accents, and fine borders.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/linear.app/DESIGN.md",
    style: {
      background: "#010102",
      color: "#f7f8f8",
      accent: "#5e6ad2",
      borderColor: "#23252a",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "lovable",
    name: "Lovable",
    description:
      "Lovable inspired: Parchment surfaces, charcoal actions, and warm hairlines.",
    category: "Design tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/lovable/DESIGN.md",
    style: {
      background: "#f7f4ed",
      color: "#1c1c1c",
      accent: "#1c1c1c",
      borderColor: "#eceae4",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "mastercard",
    name: "Mastercard",
    description:
      "Mastercard inspired: Putty cream, warm black, and broad rounded cards.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/mastercard/DESIGN.md",
    style: {
      background: "#f3f0ee",
      color: "#141413",
      accent: "#141413",
      borderColor: "#e8e2da",
      radius: 40,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 450,
      shadow: "medium",
      opacity: 100,
    },
  },
  {
    id: "meta",
    name: "Meta",
    description:
      "Meta inspired: White surfaces, cobalt actions, and large card corners.",
    category: "Hardware",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/meta/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#1c1e21",
      accent: "#0064e0",
      borderColor: "#ced0d4",
      radius: 32,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "minimax",
    name: "MiniMax",
    description:
      "MiniMax inspired: White model panels with coral accents and soft corners.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/minimax/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#0a0a0a",
      accent: "#ff5530",
      borderColor: "#e5e7eb",
      radius: 16,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "mintlify",
    name: "Mintlify",
    description:
      "Mintlify inspired: White documentation panels with mint-green accents.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/mintlify/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#0a0a0a",
      accent: "#00d4a4",
      borderColor: "#e5e5e5",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "miro",
    name: "Miro",
    description:
      "Miro inspired: White boards with yellow accents and soft rounded cards.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/miro/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#1c1c1e",
      accent: "#ffd02f",
      borderColor: "#e0e2e8",
      radius: 16,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "mistral.ai",
    name: "Mistral AI",
    description:
      "Mistral AI inspired: Cream-yellow surfaces with orange accents and relaxed type.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/mistral.ai/DESIGN.md",
    style: {
      background: "#fff8e0",
      color: "#1f1f1f",
      accent: "#fa520f",
      borderColor: "#e6d5a8",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description:
      "MongoDB inspired: Deep teal surfaces with bright green accents.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/mongodb/DESIGN.md",
    style: {
      background: "#001e2b",
      color: "#ffffff",
      accent: "#00ed64",
      borderColor: "#1c2d38",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "nike",
    name: "Nike",
    description:
      "Nike inspired: White surfaces, black actions, and rounded controls.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/nike/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#111111",
      accent: "#111111",
      borderColor: "#cacacb",
      radius: 24,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "nintendo-2001",
    name: "Nintendo (2001)",
    description:
      "Nintendo (2001) inspired: Periwinkle panels with compact text and retro indigo borders.",
    category: "Gaming",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/nintendo-2001/DESIGN.md",
    style: {
      background: "#7a8aba",
      color: "#21242e",
      accent: "#f68d1f",
      borderColor: "#3d4f97",
      radius: 4,
      borderWidth: 2,
      padding: 12,
      fontSize: 12,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "small",
      opacity: 100,
    },
  },
  {
    id: "notion",
    name: "Notion",
    description:
      "Notion inspired: White workspace panels with purple actions and warm dividers.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/notion/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#1a1a1a",
      accent: "#5645d4",
      borderColor: "#e5e3df",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    description:
      "NVIDIA inspired: White technical tiles with green accents and angular corners.",
    category: "Hardware",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/nvidia/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#76b900",
      borderColor: "#cccccc",
      radius: 2,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "ollama",
    name: "Ollama",
    description:
      "Ollama inspired: Simple white panels with black actions and understated borders.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/ollama/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#000000",
      borderColor: "#e5e5e5",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "opencode.ai",
    name: "OpenCode",
    description:
      "OpenCode inspired: Warm near-white panels with monospaced text and tight corners.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/opencode.ai/DESIGN.md",
    style: {
      background: "#fdfcfc",
      color: "#201d1d",
      accent: "#201d1d",
      borderColor: "#e0dede",
      radius: 4,
      borderWidth: 1,
      padding: 16,
      fontSize: 16,
      fontFamily: "mono",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "pinterest",
    name: "Pinterest",
    description:
      "Pinterest inspired: White discovery cards with red accents and soft rounding.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/pinterest/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#e60023",
      borderColor: "#dadad3",
      radius: 16,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "playstation",
    name: "PlayStation",
    description:
      "PlayStation inspired: White product surfaces with blue actions and airy body text.",
    category: "Gaming",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/playstation/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#0070d1",
      borderColor: "#f3f3f3",
      radius: 8,
      borderWidth: 1,
      padding: 32,
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "posthog",
    name: "PostHog",
    description:
      "PostHog inspired: Gray-green surfaces with amber accents and compact geometry.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/posthog/DESIGN.md",
    style: {
      background: "#eeefe9",
      color: "#23251d",
      accent: "#f7a501",
      borderColor: "#bfc1b7",
      radius: 4,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "raycast",
    name: "Raycast",
    description:
      "Raycast inspired: Dark command panels with red accents and fine borders.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/raycast/DESIGN.md",
    style: {
      background: "#07080a",
      color: "#f4f4f6",
      accent: "#ff6161",
      borderColor: "#242728",
      radius: 10,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "renault",
    name: "Renault",
    description:
      "Renault inspired: White surfaces with yellow accents and precise square edges.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/renault/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#ffed00",
      borderColor: "#f2f2f2",
      radius: 0,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "replicate",
    name: "Replicate",
    description:
      "Replicate inspired: Warm paper surfaces with red-orange actions and soft corners.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/replicate/DESIGN.md",
    style: {
      background: "#f9f7f3",
      color: "#202020",
      accent: "#ea2804",
      borderColor: "#dfddda",
      radius: 10,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "resend",
    name: "Resend",
    description:
      "Resend inspired: Black email-tool panels with cool white accents and subtle borders.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/resend/DESIGN.md",
    style: {
      background: "#000000",
      color: "#fcfdff",
      accent: "#fcfdff",
      borderColor: "#0f0f0f",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "revolut",
    name: "Revolut",
    description:
      "Revolut inspired: White financial panels with indigo accents and broad corners.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/revolut/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#191c1f",
      accent: "#494fdf",
      borderColor: "#e2e2e7",
      radius: 20,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "runwayml",
    name: "Runway",
    description:
      "Runway inspired: Black creative panels with white type and minimal rounding.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/runwayml/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#ffffff",
      borderColor: "#27272a",
      radius: 8,
      borderWidth: 0,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "sanity",
    name: "Sanity",
    description:
      "Sanity inspired: Near-black content panels with coral accents and tight corners.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/sanity/DESIGN.md",
    style: {
      background: "#0b0b0b",
      color: "#ffffff",
      accent: "#f36458",
      borderColor: "#353535",
      radius: 6,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "sentry",
    name: "Sentry",
    description:
      "Sentry inspired: Deep violet panels with lime accents and medium-weight type.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/sentry/DESIGN.md",
    style: {
      background: "#1f1633",
      color: "#ffffff",
      accent: "#c2ef4e",
      borderColor: "#362d59",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 500,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "shopify",
    name: "Shopify",
    description:
      "Shopify inspired: Cream commerce panels with black actions and rounded cards.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/shopify/DESIGN.md",
    style: {
      background: "#fbfbf5",
      color: "#000000",
      accent: "#000000",
      borderColor: "#e4e4e7",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 420,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "slack",
    name: "Slack",
    description:
      "Slack inspired: Cream surfaces with aubergine accents and rounded cards.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/slack/DESIGN.md",
    style: {
      background: "#f4ede4",
      color: "#1d1d1d",
      accent: "#4a154b",
      borderColor: "#e6e6e6",
      radius: 16,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "spacex",
    name: "SpaceX",
    description:
      "SpaceX inspired: Black surfaces with white accents and restrained geometry.",
    category: "Aerospace",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/spacex/DESIGN.md",
    style: {
      background: "#000000",
      color: "#ffffff",
      accent: "#ffffff",
      borderColor: "#3a3a3f",
      radius: 4,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "spotify",
    name: "Spotify",
    description:
      "Spotify inspired: Charcoal listening panels with green accents and soft elevation.",
    category: "Media",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/spotify/DESIGN.md",
    style: {
      background: "#121212",
      color: "#ffffff",
      accent: "#1ed760",
      borderColor: "#4d4d4d",
      radius: 8,
      borderWidth: 1,
      padding: 16,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "medium",
      opacity: 100,
    },
  },
  {
    id: "starbucks",
    name: "Starbucks",
    description:
      "Starbucks inspired: Warm cream surfaces with deep green text and green actions.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/starbucks/DESIGN.md",
    style: {
      background: "#f2f0eb",
      color: "#1e3932",
      accent: "#00754a",
      borderColor: "#edebe9",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "small",
      opacity: 100,
    },
  },
  {
    id: "stripe",
    name: "Stripe",
    description:
      "Stripe inspired: White financial panels with navy ink and indigo accents.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/stripe/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#0d253d",
      accent: "#533afd",
      borderColor: "#e3e8ee",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 15,
      fontFamily: "sans",
      fontWeight: 300,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "supabase",
    name: "Supabase",
    description:
      "Supabase inspired: White technical panels with emerald accents and quiet borders.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/supabase/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#171717",
      accent: "#3ecf8e",
      borderColor: "#dfdfdf",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "superhuman",
    name: "Superhuman",
    description:
      "Superhuman inspired: White productivity panels with warm ink and deep indigo actions.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/superhuman/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#292827",
      accent: "#1b1938",
      borderColor: "#e8e4dd",
      radius: 12,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 460,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "tesla",
    name: "Tesla",
    description:
      "Tesla inspired: White surfaces, blue actions, and precise four-pixel corners.",
    category: "Automotive",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/tesla/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#171a20",
      accent: "#3e6ae1",
      borderColor: "#eeeeee",
      radius: 4,
      borderWidth: 0,
      padding: 16,
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "theverge",
    name: "The Verge",
    description:
      "The Verge inspired: Dark editorial cards with mint accents and broad rounded edges.",
    category: "Media",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/theverge/DESIGN.md",
    style: {
      background: "#131313",
      color: "#ffffff",
      accent: "#3cffd0",
      borderColor: "#309875",
      radius: 24,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 500,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "together.ai",
    name: "Together AI",
    description:
      "Together AI inspired: Deep navy panels with periwinkle accents and tight corners.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/together.ai/DESIGN.md",
    style: {
      background: "#010120",
      color: "#ffffff",
      accent: "#bdbbff",
      borderColor: "#313641",
      radius: 4,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "uber",
    name: "Uber",
    description:
      "Uber inspired: White utility panels with black actions and rounded cards.",
    category: "Commerce",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/uber/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#000000",
      borderColor: "#efefef",
      radius: 16,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "vercel",
    name: "Vercel",
    description:
      "Vercel inspired: White technical panels with dark actions and crisp hairlines.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/vercel/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#171717",
      accent: "#171717",
      borderColor: "#ebebeb",
      radius: 8,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "vodafone",
    name: "Vodafone",
    description:
      "Vodafone inspired: White surfaces with scarlet actions and readable body type.",
    category: "Telecommunications",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/vodafone/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#25282b",
      accent: "#e60000",
      borderColor: "#f2f2f2",
      radius: 6,
      borderWidth: 1,
      padding: 16,
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "voltagent",
    name: "VoltAgent",
    description:
      "VoltAgent inspired: Near-black agent panels with electric green accents.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/voltagent/DESIGN.md",
    style: {
      background: "#101010",
      color: "#f2f2f2",
      accent: "#00d992",
      borderColor: "#3d3a39",
      radius: 8,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "warp",
    name: "Warp",
    description:
      "Warp inspired: Warm charcoal panels with cream type and tight corners.",
    category: "Developer tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/warp/DESIGN.md",
    style: {
      background: "#2b2622",
      color: "#f7f5f0",
      accent: "#f7f5f0",
      borderColor: "#3f3a36",
      radius: 4,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "webflow",
    name: "Webflow",
    description:
      "Webflow inspired: White design panels with blue accents and generous spacing.",
    category: "Design tools",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/webflow/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#080808",
      accent: "#146ef5",
      borderColor: "#d8d8d8",
      radius: 8,
      borderWidth: 1,
      padding: 32,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "wired",
    name: "WIRED",
    description:
      "WIRED inspired: White editorial panels with serif text and square edges.",
    category: "Media",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/wired/DESIGN.md",
    style: {
      background: "#ffffff",
      color: "#000000",
      accent: "#000000",
      borderColor: "#e0e0e0",
      radius: 0,
      borderWidth: 1,
      padding: 20,
      fontSize: 17,
      fontFamily: "serif",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "wise",
    name: "Wise",
    description:
      "Wise inspired: Pale sage surfaces with lime accents and broad rounded cards.",
    category: "Finance",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/wise/DESIGN.md",
    style: {
      background: "#e8ebe6",
      color: "#0e0f0c",
      accent: "#9fe870",
      borderColor: "#c5edab",
      radius: 24,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "x.ai",
    name: "xAI",
    description:
      "xAI inspired: Near-black panels with white accents and restrained corners.",
    category: "AI",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/x.ai/DESIGN.md",
    style: {
      background: "#0a0a0a",
      color: "#ffffff",
      accent: "#ffffff",
      borderColor: "#212327",
      radius: 8,
      borderWidth: 1,
      padding: 24,
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
  {
    id: "zapier",
    name: "Zapier",
    description:
      "Zapier inspired: Warm cream, coffee-colored ink, and orange actions.",
    category: "Productivity",
    source:
      "https://github.com/VoltAgent/awesome-design-md/blob/8147538b4226ae41e2487a9179e3bcc1f68e8554/design-md/zapier/DESIGN.md",
    style: {
      background: "#fffefb",
      color: "#201515",
      accent: "#ff4f00",
      borderColor: "#c5c0b1",
      radius: 12,
      borderWidth: 1,
      padding: 24,
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      shadow: "none",
      opacity: 100,
    },
  },
];
