import { widgetCatalog } from "./catalog";
import { createDocument, createWidget } from "./model";
import type { StudioDocument, WidgetKind, WidgetStyle } from "./types";

/** Page starters and style presets are independent catalogs. */
export const templateCatalog = [
  {
    id: "dashboard",
    name: "Analytics overview",
    description: "Revenue trends, channel mix and recent customer activity.",
    category: "Insights",
  },
  {
    id: "revenue",
    name: "Revenue & sales",
    description: "Quarterly targets, territory performance and deal forecasts.",
    category: "Business",
  },
  {
    id: "crm",
    name: "CRM pipeline",
    description: "A deal board with account context and next follow-ups.",
    category: "Business",
  },
  {
    id: "commerce",
    name: "Commerce operations",
    description: "Fulfillment queues, inventory exceptions and order status.",
    category: "Operations",
  },
  {
    id: "finance",
    name: "Finance & expenses",
    description: "Cash position, expense approvals and department budgets.",
    category: "Business",
  },
  {
    id: "projects",
    name: "Project delivery",
    description: "Sprint work, milestone dates and release readiness.",
    category: "Operations",
  },
  {
    id: "team",
    name: "Team directory",
    description:
      "People, specialties and working hours in an editable directory.",
    category: "Workspace",
  },
  {
    id: "support",
    name: "Support inbox",
    description: "A triage queue, customer conversation and reply composer.",
    category: "Operations",
  },
  {
    id: "marketing",
    name: "Marketing performance",
    description: "Campaign results, acquisition spend and the launch calendar.",
    category: "Insights",
  },
  {
    id: "product",
    name: "Product analytics",
    description: "Activation, retention and feature adoption at a glance.",
    category: "Insights",
  },
  {
    id: "agent",
    name: "Agent workspace",
    description:
      "Research conversation, sources and a human approval checkpoint.",
    category: "AI & automation",
  },
  {
    id: "workflows",
    name: "Workflow operations",
    description: "Run health, a processing pipeline and review decisions.",
    category: "AI & automation",
  },
  {
    id: "knowledge",
    name: "Knowledge library",
    description:
      "Curated collections, useful documents and team reading notes.",
    category: "Workspace",
  },
  {
    id: "security",
    name: "Security & audit",
    description: "Access posture, audit events and permission requests.",
    category: "Administration",
  },
  {
    id: "settings",
    name: "Organization settings",
    description:
      "Organization profile, regional preferences and notifications.",
    category: "Administration",
  },
  {
    id: "onboarding",
    name: "Sign-in & onboarding",
    description:
      "A welcoming sign-in screen with a guided workspace checklist.",
    category: "Workspace",
  },
  {
    id: "billing",
    name: "SaaS plans & billing",
    description: "Three plan tiers, workspace usage and invoice history.",
    category: "Administration",
  },
] as const;

export type TemplateId = (typeof templateCatalog)[number]["id"] | "blank";
type Block = [
  kind: WidgetKind,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  subtitle?: string,
  value?: string,
  items?: string,
  treatment?: "tint" | "editorial",
];

// Each working area is deliberately composed. Newline items remain individually editable.
const compositions: Record<Exclude<TemplateId, "blank">, Block[]> = {
  dashboard: [
    [
      "stat",
      224,
      208,
      304,
      136,
      "Total revenue",
      "vs. last month",
      "$48,295",
      "+12.8%",
    ],
    [
      "stat",
      552,
      208,
      304,
      136,
      "Active customers",
      "vs. last month",
      "2,847",
      "+8.2%",
    ],
    [
      "stat",
      880,
      208,
      296,
      136,
      "Conversion rate",
      "vs. last month",
      "4.28%",
      "+0.6 pts",
    ],
    [
      "line-chart",
      224,
      368,
      616,
      328,
      "Revenue over time",
      "USD thousands · Last six months",
      "",
      "Apr | 28\nMay | 33\nJun | 31\nJul | 39\nAug | 43\nSep | 48",
    ],
    [
      "donut-chart",
      864,
      368,
      312,
      328,
      "Channel mix",
      "Share of new customers",
      "100%",
      "Organic | 48\nReferral | 32\nPaid | 20",
    ],
    [
      "table",
      224,
      720,
      616,
      256,
      "Recent transactions",
      "Latest settled invoices",
      "",
      "Customer | Plan | Amount\nAcorn Studio | Growth | $249\nOrbit Labs | Scale | $899\nFieldwork | Growth | $249",
    ],
    [
      "activity",
      864,
      720,
      312,
      256,
      "Workspace activity",
      "Today",
      "",
      "Orbit upgraded | 12 min ago\nReport shared | 48 min ago\nGoal reached | 2 hours ago",
    ],
  ],
  revenue: [
    [
      "stat",
      224,
      208,
      352,
      136,
      "Quarter booked",
      "Q3 target: $350,000",
      "$284,600",
      "81% of target",
    ],
    [
      "progress",
      600,
      208,
      576,
      136,
      "Quarterly attainment",
      "$65,400 remaining · 24 days left",
      "81",
      "",
      "tint",
    ],
    [
      "bar-chart",
      224,
      368,
      448,
      336,
      "Sales by territory",
      "Booked revenue · USD thousands",
      "",
      "East | 98\nWest | 84\nEMEA | 67\nAPAC | 35",
    ],
    [
      "table",
      696,
      368,
      480,
      336,
      "Commit forecast",
      "Deals expected this month",
      "",
      "Account | Owner | Value\nMeridian | Amira | $42,000\nSolstice | Theo | $28,500\nJuniper | Lena | $18,200\nNoble | Oscar | $12,000",
    ],
    [
      "list",
      224,
      728,
      584,
      248,
      "Closing plan",
      "Focus for this week",
      "",
      "Meridian legal review | Tuesday\nSolstice executive demo | Wednesday\nJuniper procurement | Friday",
    ],
    [
      "card",
      832,
      728,
      344,
      248,
      "Forecast confidence",
      "Updated by sales operations",
      "Review forecast",
      "Commit | $100,700\nUpside | $62,000",
      "tint",
    ],
  ],
  crm: [
    ["search", 224, 208, 616, 104, "Find a deal · Account or contact"],
    ["button", 864, 208, 312, 88, "Add opportunity", "Sample pipeline"],
    [
      "kanban",
      224,
      320,
      952,
      368,
      "September pipeline",
      "6 opportunities · $186,000 open",
      "",
      "Qualified | Acorn — $18k\nQualified | Cobalt — $24k\nDiscovery | Meridian — $42k\nDiscovery | Orbit — $32k\nProposal | Solstice — $28k\nWon | Juniper — $42k",
    ],
    [
      "avatar",
      224,
      712,
      304,
      88,
      "Amira Lewis",
      "Account lead · Meridian",
      "AL",
    ],
    [
      "card",
      224,
      824,
      304,
      152,
      "Account brief",
      "Meridian · Enterprise",
      "",
      "Champion | VP Operations",
      "tint",
    ],
    [
      "activity",
      552,
      712,
      352,
      264,
      "Next follow-ups",
      "Keep momentum",
      "",
      "Meridian | Security response\nOrbit | Solution review\nSolstice | Confirm budget owner",
    ],
    [
      "stat",
      928,
      712,
      248,
      264,
      "Win rate",
      "Last 90 days",
      "32%",
      "+4 pts",
      "tint",
    ],
  ],
  commerce: [
    [
      "alert",
      224,
      208,
      952,
      104,
      "12 orders need attention",
      "Eight await stock; four need an address check.",
      "Review queue",
      "",
      "tint",
    ],
    [
      "table",
      224,
      336,
      616,
      384,
      "Fulfillment queue",
      "Orders placed in the last 24 hours",
      "",
      "Order | Customer | Status\n#1048 | Isla Moore | Ready to pack\n#1049 | Eli Chen | Picking\n#1050 | Mia Patel | Address check\n#1051 | Noah King | Awaiting stock\n#1052 | Ava Ross | Ready to pack",
    ],
    [
      "stat",
      864,
      336,
      312,
      136,
      "Orders today",
      "24 awaiting dispatch",
      "128",
      "+18% this week",
    ],
    [
      "progress",
      864,
      496,
      312,
      224,
      "Dispatch target",
      "104 of 128 orders shipped",
      "81",
    ],
    [
      "list",
      224,
      744,
      456,
      232,
      "Inventory watch",
      "Reorder points reached",
      "",
      "Canvas tote / Sand | 8 units left\nTravel mug / Ink | 12 units left\nNotebook / Moss | 19 units left",
    ],
    [
      "activity",
      704,
      744,
      472,
      232,
      "Warehouse updates",
      "East distribution center",
      "",
      "Carrier pickup | 16:30 today\nRestock arriving | Tomorrow, 09:00",
      "tint",
    ],
  ],
  finance: [
    [
      "stat",
      224,
      208,
      408,
      200,
      "Available cash",
      "Across 3 operating accounts",
      "$842,190",
      "6.4 months runway",
      "tint",
    ],
    [
      "table",
      656,
      208,
      520,
      360,
      "Expenses to approve",
      "4 requests · $6,890 total",
      "",
      "Request | Team | Amount\nCloud hosting | Engineering | $3,200\nOffsite venue | People | $2,100\nResearch tools | Design | $890\nTravel | Sales | $700",
    ],
    [
      "list",
      224,
      432,
      408,
      256,
      "Cash movements",
      "Upcoming this week",
      "",
      "Payroll | $92,000 · Sep 10\nCustomer receipts | $148,200 · Sep 12\nVendor payments | $24,800 · Sep 14",
    ],
    [
      "progress",
      656,
      592,
      248,
      160,
      "Engineering budget",
      "Month to date",
      "68",
    ],
    ["progress", 928, 592, 248, 160, "Sales budget", "Month to date", "42"],
    [
      "card",
      224,
      712,
      408,
      264,
      "Month-end close",
      "September 2026",
      "Open checklist",
      "Reconciliation | Complete\nController review | Sep 30",
    ],
    [
      "table",
      656,
      776,
      520,
      200,
      "Recent reimbursements",
      "Paid this week",
      "",
      "Employee | Amount | Paid\nTheo Kim | $240 | Sep 4\nLena Ortiz | $185 | Sep 5",
    ],
  ],
  projects: [
    [
      "progress",
      224,
      208,
      616,
      136,
      "Release 2.4 readiness",
      "18 of 25 acceptance checks complete",
      "72",
      "",
      "tint",
    ],
    [
      "stat",
      864,
      208,
      312,
      136,
      "Days to launch",
      "September 18, 2026",
      "12",
      "On track",
    ],
    [
      "kanban",
      224,
      368,
      616,
      368,
      "Sprint 18",
      "Design, build and validate",
      "",
      "Ready | Export docs\nReady | Empty-state copy\nIn progress | Billing navigation\nIn progress | Usage charts\nReview | Keyboard pass\nReview | Release notes",
    ],
    [
      "calendar",
      864,
      368,
      312,
      416,
      "Release calendar",
      "September 2026",
      "18",
      "Design freeze | Sep 10\nLaunch review | Sep 16",
    ],
    [
      "activity",
      224,
      760,
      616,
      216,
      "Delivery notes",
      "Cross-team handoffs",
      "",
      "Design approved navigation | Amira · Today\nAPI contract frozen | Theo · Yesterday",
    ],
    [
      "card",
      864,
      808,
      312,
      168,
      "Release owner",
      "Lena Ortiz · Product",
      "Contact owner",
      "",
      "tint",
    ],
  ],
  team: [
    ["search", 224, 208, 616, 104, "Search people · Name, role or location"],
    [
      "select",
      864,
      208,
      312,
      104,
      "Department",
      "",
      "All departments",
      "All departments\nDesign\nEngineering\nProduct\nOperations",
    ],
    [
      "avatar",
      224,
      320,
      296,
      88,
      "Amira Lewis",
      "Design lead · New York",
      "AL",
      "",
      "tint",
    ],
    [
      "list",
      224,
      416,
      296,
      152,
      "Working together",
      "",
      "",
      "Design systems | 09:00–17:00 ET\nFocus | Navigation patterns",
    ],
    [
      "avatar",
      552,
      320,
      296,
      88,
      "Theo Kim",
      "Staff engineer · Toronto",
      "TK",
      "",
      "tint",
    ],
    [
      "list",
      552,
      416,
      296,
      152,
      "Working together",
      "",
      "",
      "Platform | 09:00–17:00 ET\nFocus | Release reliability",
    ],
    [
      "avatar",
      880,
      320,
      296,
      88,
      "Lena Ortiz",
      "Product manager · Austin",
      "LO",
      "",
      "tint",
    ],
    [
      "list",
      880,
      416,
      296,
      152,
      "Working together",
      "",
      "",
      "Product | 09:00–17:00 CT\nFocus | Customer onboarding",
    ],
    [
      "avatar",
      224,
      592,
      296,
      88,
      "Oscar Reed",
      "Researcher · London",
      "OR",
      "",
      "tint",
    ],
    [
      "list",
      224,
      688,
      296,
      152,
      "Working together",
      "",
      "",
      "Research | 09:00–17:00 GMT\nFocus | Discovery interviews",
    ],
    [
      "avatar",
      552,
      592,
      296,
      88,
      "Priya Shah",
      "Operations lead · Berlin",
      "PS",
      "",
      "tint",
    ],
    [
      "list",
      552,
      688,
      296,
      152,
      "Working together",
      "",
      "",
      "Operations | 09:00–17:00 CET\nFocus | Team enablement",
    ],
    [
      "avatar",
      880,
      592,
      296,
      88,
      "Jules Martin",
      "Engineer · Paris",
      "JM",
      "",
      "tint",
    ],
    [
      "list",
      880,
      688,
      296,
      152,
      "Working together",
      "",
      "",
      "Frontend | 09:00–17:00 CET\nFocus | Accessible controls",
    ],
    [
      "alert",
      224,
      864,
      952,
      112,
      "Make room for focused work",
      "Core collaboration hours: 10:00–12:00 ET. Profiles and availability are sample data.",
    ],
  ],
  support: [
    [
      "list",
      224,
      208,
      280,
      536,
      "Open conversations",
      "8 assigned to you",
      "",
      "Isla / Export unavailable | Urgent · 4 min\nEli / Invoice question | 18 min\nMia / Invite expired | 42 min\nNoah / Plan upgrade | 1 hour\nAva / API limits | 2 hours",
    ],
    [
      "chat",
      528,
      208,
      648,
      392,
      "#2048 · Export unavailable",
      "Isla Moore · Growth plan",
      "",
      "Isla | My report export has been pending since this morning.\nYou | Thanks, Isla. Is it the September workspace report?\nIsla | Yes, the CSV for our operations team.\nYou | I have the details. I will check the export status next.",
    ],
    [
      "composer",
      528,
      624,
      648,
      176,
      "Reply to Isla",
      "Write a helpful response…",
      "Send reply",
    ],
    [
      "stat",
      224,
      768,
      280,
      208,
      "First response",
      "Team median today",
      "12 min",
      "Target: under 15 min",
      "tint",
    ],
    [
      "card",
      528,
      824,
      376,
      152,
      "Customer context",
      "Isla Moore · Acorn Studio",
      "",
      "Member since | March 2025",
    ],
    ["button", 928, 824, 248, 152, "Mark resolved", "Interface preview"],
  ],
  marketing: [
    [
      "stat",
      224,
      208,
      304,
      136,
      "Attributed pipeline",
      "September campaigns",
      "$186k",
      "+24% vs. August",
    ],
    [
      "stat",
      552,
      208,
      304,
      136,
      "Cost per lead",
      "Blended acquisition",
      "$42",
      "Down 12%",
    ],
    [
      "stat",
      880,
      208,
      296,
      136,
      "Qualified leads",
      "112 sales accepted",
      "486",
      "+19% vs. August",
    ],
    [
      "table",
      224,
      368,
      952,
      264,
      "Campaign scorecard",
      "Pipeline attribution · 30-day window",
      "",
      "Campaign | Channel | Spend | Leads | Pipeline\nAutumn launch | Paid search | $8,200 | 184 | $72,000\nBuilder stories | Newsletter | $1,400 | 126 | $48,000\nOperations summit | Events | $9,800 | 92 | $44,000\nPartner spotlight | Referral | $1,000 | 84 | $22,000",
    ],
    [
      "bar-chart",
      224,
      656,
      448,
      320,
      "Acquisition spend",
      "USD thousands by channel",
      "",
      "Search | 8.2\nSocial | 4.6\nEvents | 9.8",
    ],
    [
      "activity",
      696,
      656,
      480,
      320,
      "Launch schedule",
      "Upcoming moments",
      "",
      "Sep 9 | Customer story live\nSep 12 | Partner webinar\nSep 16 | Product launch email\nSep 21 | Campaign retrospective",
      "tint",
    ],
  ],
  product: [
    [
      "bar-chart",
      224,
      208,
      584,
      328,
      "Activation funnel",
      "New accounts this month",
      "",
      "Signup | 2400\nSetup | 1820\nInvite | 1260\nFirst value | 980",
    ],
    [
      "stat",
      832,
      208,
      344,
      136,
      "Activation rate",
      "First value within 7 days",
      "40.8%",
      "+6.2 pts",
    ],
    [
      "progress",
      832,
      368,
      344,
      168,
      "Week 4 retention",
      "September signup cohort",
      "64",
      "",
      "tint",
    ],
    [
      "table",
      224,
      560,
      584,
      272,
      "Feature adoption",
      "Weekly active workspaces",
      "",
      "Feature | Adoption | Change\nReports | 78% | +4 pts\nAutomations | 46% | +9 pts\nShared boards | 62% | +3 pts\nExports | 34% | +2 pts",
    ],
    [
      "list",
      832,
      560,
      344,
      416,
      "Learning agenda",
      "Active experiments",
      "",
      "Guided setup | +8% activation\nInvite prompt | Measuring\nTemplate discovery | Recruiting\nNext review | September 12",
    ],
    [
      "alert",
      224,
      856,
      584,
      120,
      "Activation is improving",
      "Guided setup is the largest contributor. Validate across the next two cohorts.",
    ],
  ],
  agent: [
    [
      "chat",
      224,
      208,
      584,
      440,
      "Research assistant",
      "Onboarding benchmark · Sample conversation",
      "",
      "You | Compare our onboarding with three common product-led patterns.\nAssistant | I can summarize the supplied research and identify measurable improvements.\nYou | Focus on time to first value and team invitations.\nAssistant | The brief proposes guided setup, a sample project and a contextual invite prompt. Each recommendation includes a source and a metric.",
    ],
    [
      "agent",
      832,
      208,
      344,
      208,
      "Research agent",
      "Sources supplied by your team",
      "Ready",
      "Scope | 3 reference documents\nMode | Read-only research",
      "tint",
    ],
    [
      "approval",
      832,
      440,
      344,
      320,
      "Share research brief",
      "Review before sharing with the product team.",
      "Awaiting review",
      "Destination | Product workspace\nArtifact | Onboarding brief",
    ],
    [
      "composer",
      224,
      672,
      584,
      184,
      "Ask a follow-up question",
      "Refine the comparison or ask for a source…",
      "Send prompt",
    ],
    [
      "file",
      832,
      784,
      344,
      80,
      "Onboarding brief.pdf",
      "8 pages · Prepared just now",
      "PDF",
    ],
    [
      "file",
      832,
      888,
      344,
      88,
      "Interview notes.txt",
      "12 interviews · Team source",
      "TXT",
    ],
    [
      "alert",
      224,
      880,
      584,
      96,
      "You stay in control",
      "Sample assistant. No model call or external action is connected.",
    ],
  ],
  workflows: [
    [
      "alert",
      224,
      208,
      952,
      96,
      "All systems operational",
      "One run is paused for a human decision; no active incidents.",
      "Updated 1 min ago",
      "",
      "tint",
    ],
    [
      "kanban",
      224,
      328,
      952,
      280,
      "Invoice intake workflow",
      "Document → validation → review",
      "",
      "Received | Extract invoice fields\nValidated | Match vendor record\nReview | Approve invoice #881\nComplete | Sync approved payment",
    ],
    [
      "table",
      224,
      632,
      584,
      344,
      "Recent runs",
      "Sample execution history",
      "",
      "Run | Workflow | Status | Duration\n#0841 | Invoice intake | Paused | 12s\n#0840 | Lead routing | Complete | 3s\n#0839 | Document sync | Complete | 8s\n#0838 | Invoice intake | Complete | 11s",
    ],
    [
      "stat",
      832,
      632,
      344,
      152,
      "Queue health",
      "Processed in the last hour",
      "248",
      "No retries pending",
    ],
    [
      "card",
      832,
      808,
      344,
      168,
      "Decision required",
      "Invoice #881 exceeds the approval threshold.",
      "Review run",
      "",
      "tint",
    ],
  ],
  knowledge: [
    [
      "search",
      224,
      208,
      952,
      104,
      "Search the library · Guides, decisions and playbooks",
    ],
    [
      "card",
      224,
      328,
      456,
      248,
      "Start with the essentials",
      "A shared foundation for the whole team",
      "Explore collection",
      "Company handbook | 14 guides\nNew starter path | 6 steps",
      "tint",
    ],
    [
      "list",
      704,
      328,
      472,
      248,
      "Curated collections",
      "Maintained by your team",
      "",
      "Design practice | 24 resources\nEngineering playbooks | 36 resources\nCustomer learning | 18 resources",
    ],
    [
      "file",
      224,
      600,
      456,
      104,
      "Product principles.md",
      "Product · Updated Sep 5",
      "MD",
    ],
    [
      "file",
      224,
      728,
      456,
      104,
      "Incident response.pdf",
      "Engineering · Updated Sep 4",
      "PDF",
    ],
    [
      "file",
      224,
      856,
      456,
      120,
      "Research repository.txt",
      "Design · Updated Sep 2",
      "TXT",
    ],
    [
      "text",
      704,
      600,
      472,
      376,
      "From the library desk",
      "Reading note / September",
      "Good documentation makes the next decision easier. This month we are collecting the context behind product tradeoffs, alongside the decisions themselves.",
      "Reading group | Thursdays at 14:00\nContribute | Share a short field note\nCollection owner | Oscar Reed",
      "editorial",
    ],
  ],
  security: [
    [
      "stat",
      224,
      208,
      288,
      136,
      "Security posture",
      "2 recommendations open",
      "98/100",
      "Healthy",
    ],
    [
      "progress",
      536,
      208,
      328,
      136,
      "MFA enrollment",
      "47 of 48 members enrolled",
      "98",
    ],
    ["badge", 888, 208, 288, 136, "SSO enforced", "", "", "", "tint"],
    [
      "table",
      224,
      368,
      640,
      384,
      "Audit events",
      "Workspace access · Last 24 hours",
      "",
      "Time | Actor | Event\n14:32 | Amira Lewis | Role updated\n13:58 | Theo Kim | SSO sign-in\n12:40 | Service account | Token rotated\n11:16 | Lena Ortiz | Member invited\n09:24 | Oscar Reed | Report exported",
    ],
    [
      "approval",
      888,
      368,
      288,
      384,
      "Access review",
      "Temporary elevated role requested.",
      "Pending",
      "Member | Jules Martin\nRole | Project admin\nDuration | 24 hours\nReason | Release support",
    ],
    [
      "list",
      224,
      776,
      640,
      200,
      "Recommended actions",
      "Improve workspace protection",
      "",
      "Complete MFA enrollment | 1 member remaining\nReview dormant tokens | 2 tokens over 90 days",
    ],
    [
      "card",
      888,
      776,
      288,
      200,
      "Policy center",
      "Last reviewed Sep 1",
      "View policies",
      "",
      "tint",
    ],
  ],
  settings: [
    [
      "card",
      224,
      208,
      584,
      152,
      "Organization profile",
      "These details appear on shared workspace pages.",
      "",
      "Workspace ID | northstar-team",
      "tint",
    ],
    ["input", 224, 384, 280, 104, "Organization name", "", "Northstar"],
    ["input", 528, 384, 280, 104, "Workspace URL", "", "northstar-team"],
    ["input", 224, 512, 584, 104, "Contact email", "", "team@example.com"],
    [
      "select",
      224,
      640,
      280,
      104,
      "Time zone",
      "",
      "America/New_York",
      "America/New_York\nEurope/London\nAsia/Singapore",
    ],
    [
      "select",
      528,
      640,
      280,
      104,
      "Week starts on",
      "",
      "Monday",
      "Monday\nSunday",
    ],
    [
      "switch",
      224,
      768,
      584,
      88,
      "Weekly activity digest",
      "Send a summary to workspace administrators",
      "on",
    ],
    ["button", 224, 880, 200, 80, "Save changes", "Interface preview"],
    [
      "list",
      832,
      208,
      344,
      288,
      "Organization access",
      "Manage who can do what",
      "",
      "Members | 48 active\nAdministrators | 3 members\nGuests | 6 active\nDefault role | Member",
    ],
    [
      "card",
      832,
      520,
      344,
      264,
      "Workspace preferences",
      "Defaults for new members",
      "Review preferences",
      "Language | English\nSession timeout | 12 hours",
    ],
    [
      "alert",
      832,
      808,
      344,
      168,
      "Sample settings",
      "Controls demonstrate a settings page. No account configuration is changed.",
    ],
  ],
  onboarding: [
    [
      "navbar",
      40,
      32,
      1120,
      64,
      "Northstar",
      "A workspace for thoughtful teams",
      "N",
      "Help center",
    ],
    [
      "heading",
      64,
      152,
      512,
      136,
      "Your next chapter starts here.",
      "Bring your people, projects and ideas into one shared space.",
      "",
      "",
      "editorial",
    ],
    [
      "text",
      64,
      312,
      512,
      184,
      "Less setup. More momentum.",
      "Built for the way teams work",
      "Begin with a useful template, invite a teammate and make your first shared decision.",
      "",
      "tint",
    ],
    [
      "list",
      64,
      520,
      512,
      248,
      "A simple first day",
      "Your workspace checklist",
      "",
      "01 / Create your account | Use your work email\n02 / Choose a starting point | Pick a page template\n03 / Invite your team | Build something together",
    ],
    [
      "login",
      640,
      152,
      496,
      456,
      "Welcome back",
      "Sign in to your Northstar workspace.",
      "Sign in",
    ],
    ["divider", 640, 632, 496, 40, "New to Northstar?"],
    ["button", 640, 696, 496, 80, "Create an account", "Interface preview"],
    [
      "progress",
      64,
      792,
      512,
      160,
      "Workspace setup",
      "Start with your account",
      "0",
    ],
    [
      "alert",
      640,
      800,
      496,
      152,
      "A safe place to explore",
      "This sign-in page is a prototype. Authentication and account creation are not connected.",
    ],
  ],
  billing: [
    [
      "navbar",
      40,
      24,
      1120,
      64,
      "Northstar / Billing",
      "Plans that grow with your team",
      "AL",
      "Workspace\nBilling help",
    ],
    [
      "heading",
      64,
      112,
      1072,
      72,
      "SaaS plans & billing",
      "Choose your next stage. All prices below are sample monthly prices.",
    ],
    [
      "pricing",
      64,
      208,
      336,
      384,
      "Starter",
      "For small teams finding their rhythm",
      "$19",
      "5 members\n10 shared projects\nCommunity support",
    ],
    [
      "pricing",
      432,
      208,
      336,
      384,
      "Growth",
      "For teams building together every day",
      "$49",
      "25 members\nUnlimited projects\nWorkflow automations\nPriority support",
      "tint",
    ],
    [
      "pricing",
      800,
      208,
      336,
      384,
      "Scale",
      "For organizations with more to coordinate",
      "$129",
      "100 members\nSSO and audit logs\nAdvanced permissions\nDedicated onboarding",
    ],
    [
      "progress",
      64,
      616,
      336,
      152,
      "Member usage",
      "18 of 25 Growth seats used",
      "72",
    ],
    [
      "card",
      64,
      792,
      336,
      184,
      "Current subscription",
      "Growth · Renews October 1",
      "Manage plan",
      "Payment method | Visa ending 4242",
    ],
    [
      "table",
      432,
      616,
      704,
      216,
      "Invoice history",
      "Sample billing records",
      "",
      "Invoice | Date | Amount | Status\nINV-0901 | Sep 1, 2026 | $49 | Paid\nINV-0801 | Aug 1, 2026 | $49 | Paid",
    ],
    [
      "alert",
      432,
      856,
      704,
      120,
      "Billing preview",
      "Plan selection and payment controls are examples. No purchase or subscription change is connected.",
    ],
  ],
};

const navigation: Partial<Record<TemplateId, string>> = {
  crm: "Pipeline\nAccounts\nContacts\nFollow-ups\nReports",
  commerce: "Orders\nInventory\nFulfillment\nReturns\nCustomers",
  finance: "Cash overview\nExpenses\nBudgets\nVendors\nReports",
  projects: "Delivery\nMy tasks\nRoadmap\nTeam\nArchive",
  team: "People\nDepartments\nTime off\nWorking hours\nSettings",
  support: "Inbox\nAssigned to me\nWaiting\nResolved\nHelp center",
  agent: "Workspace\nConversations\nSources\nApprovals\nRun history",
  workflows: "Operations\nWorkflows\nRuns\nConnections\nAlerts",
  knowledge: "Library\nCollections\nRecently updated\nSaved\nContributors",
  security: "Security\nAudit log\nAccess reviews\nPolicies\nIntegrations",
  settings: "General\nMembers\nPermissions\nNotifications\nBilling",
};

/** Fresh editable documents, with stable initial IDs for server/client hydration. */
export function createTemplate(id: TemplateId): StudioDocument {
  const doc = createDocument();
  if (id === "blank") return doc;
  const descriptor = templateCatalog.find((entry) => entry.id === id);
  if (!descriptor) throw new Error(`Unknown template: ${id}`);
  doc.name = descriptor.name;
  const [accent, page, ink, tint, radius] = [
    "finance",
    "commerce",
    "billing",
  ].includes(id)
    ? (["#23715c", "#f4f7f4", "#203c32", "#e5f1e9", 8] as const)
    : ["crm", "marketing", "knowledge"].includes(id)
      ? (["#925409", "#faf7f1", "#443522", "#f9edce", 8] as const)
      : ["team", "agent", "onboarding"].includes(id)
        ? (["#784785", "#f8f5f9", "#382640", "#f0e8f4", 16] as const)
        : ["workflows", "security", "projects"].includes(id)
          ? (["#345d72", "#f3f6f7", "#233743", "#e6eff3", 4] as const)
          : (["#315bc7", "#f5f7fb", "#1c2b48", "#eaf0fd", 12] as const);
  doc.background = page;
  const blocks: Block[] = [];
  if (id !== "onboarding" && id !== "billing") {
    blocks.push(
      [
        "sidebar",
        0,
        0,
        192,
        1000,
        "Northstar",
        "Sample workspace",
        "N",
        navigation[id] ?? "Overview\nReports\nSegments\nActivity\nSettings",
      ],
      [
        "navbar",
        224,
        24,
        952,
        64,
        descriptor.category,
        "Northstar / Workspace",
        "AL",
        "Help\nShare",
      ],
      ["heading", 224, 112, 952, 72, doc.name, descriptor.description],
    );
  }
  blocks.push(...compositions[id]);
  for (const [
    kind,
    x,
    y,
    width,
    height,
    title,
    subtitle = "",
    value = "",
    items = "",
    treatment,
  ] of blocks) {
    const definition = widgetCatalog.find((entry) => entry.kind === kind);
    if (!definition) throw new Error(`Missing widget definition: ${kind}`);
    const widget = createWidget(definition, undefined, x, y);
    Object.assign(widget, {
      id: `template-${id}-${doc.widgets.length}`,
      name: title,
      width,
      height,
    });
    widget.content = { title, subtitle, value, items, image: "", imageAlt: "" };
    const style: Partial<WidgetStyle> = {
      accent,
      color: ink,
      radius,
      padding: 16,
      fontSize: 13,
    };
    if (kind === "activity") style.padding = 12;
    if (kind === "search" || kind === "input" || kind === "select")
      style.padding = 12;
    if (kind === "list" && height <= 152) style.padding = 10;
    else if (kind === "list" && height <= 232) style.padding = 12;
    if (
      (kind === "alert" && height <= 104) ||
      (kind === "file" && height <= 88) ||
      (kind === "card" && height <= 184)
    )
      style.padding = 12;
    if (treatment === "tint")
      Object.assign(style, { background: tint, borderWidth: 0 });
    if (treatment === "editorial")
      Object.assign(style, { fontFamily: "serif", background: "#fffdf8" });
    if (kind === "heading" || kind === "divider")
      Object.assign(style, { background: page, borderWidth: 0, padding: 0 });
    if (kind === "sidebar")
      Object.assign(style, {
        background: "#ffffff",
        borderWidth: 0,
        radius: 0,
      });
    if (kind === "navbar") style.padding = 16;
    if (kind === "login")
      Object.assign(style, { padding: 32, shadow: "medium" });
    Object.assign(widget.style, style);
    doc.widgets.push(widget);
  }
  return doc;
}
