import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { widgetCatalog, designPresets } from "./engine";
import { listSavedComponents } from "./store";

const here = dirname(fileURLToPath(import.meta.url));
// Overridable so manual test runs don't overwrite the real, committed skill docs.
const SKILL_REFS_DIR =
  process.env["NIMBUS_SKILL_REFS_DIR"] ??
  join(here, "..", "..", "..", ".claude", "skills", "nimbus-ui-designer", "references");

function byCategory<T extends { category: string }>(items: readonly T[]): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const list = map.get(item.category) ?? [];
    list.push(item);
    map.set(item.category, list);
  }
  return map;
}

/** Regenerated from the live catalog — never hand-edit this file. */
export function generateComponentsReference(): string {
  const lines = [
    "# Nimbus Studio widget catalog",
    "",
    "Auto-generated by `packages/mcp-nimbus-studio/src/skill-sync.ts` — do not hand-edit.",
    "Every `kind` below is a valid value for the `add_widget` tool's `kind` argument.",
    "Content fields are the same four for every kind: `title`, `subtitle`, `value`, `items`",
    "(one item per line; a row's columns are separated by ` | `).",
    "",
  ];
  const grouped = byCategory(widgetCatalog);
  for (const [category, items] of [...grouped.entries()].sort()) {
    lines.push(`## ${category}`, "");
    for (const item of items.sort((a, b) => a.kind.localeCompare(b.kind))) {
      lines.push(
        `- \`${item.kind}\` — **${item.name}** (default ${item.width}×${item.height}). ${item.description}`,
      );
    }
    lines.push("");
  }
  lines.push("## Style presets", "");
  lines.push(
    `${designPresets.length} presets are available by \`id\` for the \`presetId\` argument on \`add_widget\`/\`update_widget\`. A few per family:`,
    "",
  );
  const presetGroups = byCategory(designPresets);
  for (const [category, items] of [...presetGroups.entries()].sort()) {
    const sample = items.slice(0, 3).map((item) => `\`${item.id}\``).join(", ");
    lines.push(`- **${category}** (${items.length}): ${sample}${items.length > 3 ? ", …" : ""}`);
  }
  lines.push("", `Full preset id list: call the \`list_style_presets\` tool.`, "");
  return lines.join("\n");
}

/** Regenerated after every `save_component` call — grows as agents save more. */
export function generateSavedComponentsReference(): string {
  const saved = listSavedComponents();
  const lines = [
    "# Saved reusable components",
    "",
    "Auto-generated by `packages/mcp-nimbus-studio/src/skill-sync.ts` — do not hand-edit.",
    "Each entry below was composed and saved by a coding agent via the `save_component`",
    "tool, from existing catalog widgets. Insert one into any project with",
    "`insert_saved_component` instead of rebuilding it from scratch.",
    "",
  ];
  if (saved.length === 0) {
    lines.push("_None saved yet. Use `save_component` after building something reusable._");
  } else {
    for (const entry of saved) {
      lines.push(
        `## \`${entry.id}\` — ${entry.name}`,
        "",
        entry.description || "_(no description given)_",
        "",
        `- Size: ${entry.width}×${entry.height}`,
        `- Widgets: ${entry.widgets.length} (${[...new Set(entry.kinds)].join(", ")})`,
        `- Saved: ${entry.createdAt}`,
        "",
      );
    }
  }
  return lines.join("\n");
}

export function syncSkillReferences(): void {
  mkdirSync(SKILL_REFS_DIR, { recursive: true });
  writeFileSync(join(SKILL_REFS_DIR, "components.md"), generateComponentsReference() + "\n", "utf8");
  writeFileSync(join(SKILL_REFS_DIR, "saved-components.md"), generateSavedComponentsReference() + "\n", "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  syncSkillReferences();
  console.log("Skill references regenerated.");
}
