async (page) => {
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  if(await page.getByRole('button',{name:'Close export',exact:true}).count()) await page.getByRole('button',{name:'Close export',exact:true}).click();
  await page.locator('.studio-project-button').click();
  await page.getByRole('button', { name: 'New blank page', exact: true }).click();
  await page.getByRole('button', { name: 'Add Statistic', exact: true }).click();
  await page.getByRole('combobox', { name: 'Style preset', exact: true }).selectOption('linear.app');
  await page.getByRole('tab', { name: 'Content', exact: true }).click();
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Annual revenue');
  await page.getByRole('textbox', { name: 'Value or button label', exact: true }).fill('$125,000');
  await page.getByRole('tab', { name: 'Design', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Corner radius', exact: true }).fill('24');
  await page.getByRole('spinbutton', { name: 'Corner radius', exact: true }).press('Tab');
  const first = page.locator('.studio-canvas-widget').first();
  assert((await first.innerText()).includes('Annual revenue'), 'Edited text is missing from canvas');
  await first.focus();
  const beforeX = Number(await page.getByRole('spinbutton', { name: 'X position', exact: true }).inputValue());
  await first.press('ArrowRight');
  assert(Number(await page.getByRole('spinbutton', { name: 'X position', exact: true }).inputValue()) === beforeX + 1, 'Keyboard nudge failed');
  const box = await first.boundingBox();
  await page.mouse.move(box.x + box.width/2, box.y + box.height/2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width/2 + 50, box.y + box.height/2 + 40, {steps:8});
  await page.mouse.up();
  const afterX = Number(await page.getByRole('spinbutton', { name: 'X position', exact: true }).inputValue());
  assert(afterX > beforeX + 20, 'Pointer drag failed');
  const widthBefore = Number(await page.getByRole('spinbutton', { name: 'Width', exact: true }).inputValue());
  const handle = await page.getByRole('button', {name:'Resize Statistic',exact:true}).boundingBox();
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);
  await page.mouse.down();await page.mouse.move(handle.x+handle.width/2+60,handle.y+handle.height/2+20,{steps:6});await page.mouse.up();
  assert(Number(await page.getByRole('spinbutton', {name:'Width',exact:true}).inputValue())>widthBefore,'Resize drag failed');
  await page.getByRole('button', {name:'Undo',exact:true}).click();
  assert(Number(await page.getByRole('spinbutton', {name:'Width',exact:true}).inputValue())===widthBefore,'Resize undo must restore geometry in one step');
  await page.getByRole('button', {name:'Redo',exact:true}).click();
  await page.getByRole('button', {name:'Add Button',exact:true}).click();
  await page.getByRole('combobox', {name:'Style preset',exact:true}).selectOption('stripe');
  await page.getByRole('spinbutton', {name:'Y position',exact:true}).fill('520');
  await page.getByRole('spinbutton', {name:'Y position',exact:true}).press('Tab');
  await page.getByRole('tab', {name:'Motion',exact:true}).click();
  await page.getByRole('combobox', {name:'On load',exact:true}).selectOption('fade');
  await page.getByRole('combobox', {name:'On hover',exact:true}).selectOption('lift');
  await page.getByRole('button', {name:'Export code',exact:true}).click();
  const react = await page.getByRole('textbox', {name:'Generated code',exact:true}).inputValue();
  assert(react.includes('Annual revenue') && react.includes('125,000'), 'React export missing edited content');
  assert(!react.includes('from "@nimbus'), 'React export has Nimbus dependency');
  await page.getByRole('button', {name:'Standalone HTML',exact:true}).click();
  const html = await page.getByRole('textbox', {name:'Generated code',exact:true}).inputValue();
  assert(html.includes('<!doctype html>') && html.includes('nw-fade'),'HTML export invalid or missing motion');
  await page.getByRole('button', {name:'Nimbus project',exact:true}).click();
  const project = JSON.parse(await page.getByRole('textbox', {name:'Generated code',exact:true}).inputValue());
  assert(project.widgets.length===2 && project.widgets[0].presetId==='linear.app' && project.widgets[1].presetId==='stripe','Mixed styles not retained');
  assert(project.widgets[0].style.radius===24,'Radius not retained');
  await page.getByRole('button', {name:'Close export',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('.studio-save-state')?.textContent === 'Saved locally');
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('.studio-canvas-widget').length===2);
  assert((await page.locator('.studio-canvas-widget').first().innerText()).includes('Annual revenue'),'Reload lost changes');
  await page.getByRole('button',{name:'Mobile viewport',exact:true}).click();
  const frame=page.frameLocator('iframe[title="Live page preview"]');
  await frame.locator('.nw-node').first().waitFor();
  const positions=await frame.locator('.nw-node').evaluateAll(nodes=>nodes.map(n=>({top:n.getBoundingClientRect().top,left:n.getBoundingClientRect().left,width:n.getBoundingClientRect().width})));
  assert(positions[1].top>positions[0].top && positions.every(p=>p.width<=390),'Mobile stacking failed');
  await page.getByRole('button',{name:'Back to editing',exact:true}).click();
  await page.getByRole('button',{name:'Add Image',exact:true}).click();
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await page.getByLabel('Upload widget image',{exact:true}).setInputFiles('output/playwright/nimbus-studio-desktop.png');
  await page.locator('.studio-upload-preview').waitFor();
  await page.getByRole('textbox',{name:'Image description (alt text)',exact:true}).fill('Uploaded logo test');
  await page.getByRole('button',{name:'Export code',exact:true}).click();
  await page.getByRole('button',{name:'Standalone HTML',exact:true}).click();
  const imageHtml=await page.getByRole('textbox',{name:'Generated code',exact:true}).inputValue();
  assert(imageHtml.includes('data:image/png;base64,') && imageHtml.includes('Uploaded logo test'),'Upload not portable');
  await page.getByRole('button',{name:'Close export',exact:true}).click();
  await page.screenshot({path:'output/playwright/nimbus-mixed-widgets.png'});
  console.log(JSON.stringify({result:'PASS',checks:['insert','mixed presets','content','radius','keyboard nudge','pointer move','pointer resize','undo','redo','motion','React export','HTML export','JSON export','save and reload','mobile stacking','image upload and export']}));
}
