import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, posix } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { runInNewContext } from "node:vm";
import { crc32 as referenceCrc32 } from "node:zlib";
import { canonicalSourceText } from './source-text.ts';
import { createDocument, createWidget } from "../../packages/application-shell/src/studio/model.ts";
import { widgetCatalog } from "../../packages/application-shell/src/studio/catalog.ts";
import { parseProject } from "../../packages/application-shell/src/studio/project.ts";

const root = fileURLToPath(new URL("../../", import.meta.url));
const studio = join(root, "packages/application-shell/src/studio");
const sourceFiles = ["render.ts", "types.ts", "model.ts", "export.ts"];
function snapshot() {
  return Object.fromEntries([
    ...sourceFiles.map((name) => [name, canonicalSourceText(readFileSync(join(studio, name), "utf8"))]),
    ["LICENSE", canonicalSourceText(readFileSync(join(root, "LICENSE"), "utf8"))],
    ["THIRD_PARTY_NOTICES.md", canonicalSourceText(readFileSync(join(root, "THIRD_PARTY_NOTICES.md"), "utf8"))],
  ]);
}

// Mechanical generation lives in this owned file; no Vite-only raw imports or Node code in the client.
if (process.argv.includes("--sync-runtime")) {
  writeFileSync(join(studio, "runtime-source.ts"),
    "// Generated by tools/studio/package-export.test.ts --sync-runtime. Do not edit by hand.\n" +
    "export const RUNTIME_SOURCE: Record<string, string> = " + JSON.stringify(snapshot(), null, 2) + ";\n");
} else {
  const zip = await import("../../packages/application-shell/src/studio/zip.ts");
  const pkg = await import("../../packages/application-shell/src/studio/package-export.ts");
  const exporter = await import("../../packages/application-shell/src/studio/export.ts");
  const { RUNTIME_SOURCE } = await import("../../packages/application-shell/src/studio/runtime-source.ts");

  function project() {
    const doc = createDocument();
    const widget = createWidget(widgetCatalog.find((entry) => entry.kind === "button")!);
    widget.id = "next";
    Object.assign(widget, { actions: { click: "second", "item:0": "second" } });
    doc.widgets = [widget];
    return { version: 2 as const, name: "Portable prototype", startPageId: "first", pages: [
      { id: "first", document: doc },
      { id: "second", document: { ...createDocument(), name: "Second page" } },
    ] };
  }

  // Independent ZIP reader checks central directory offsets and CRC values using node:zlib.
  function unzip(bytes: Uint8Array) {
    const buffer = Buffer.from(bytes);
    const end = buffer.length - 22;
    assert.equal(buffer.readUInt32LE(end), 0x06054b50);
    const files = new Map<string, Buffer>();
    let offset = buffer.readUInt32LE(end + 16);
    for (let i = 0; i < buffer.readUInt16LE(end + 10); i++) {
      assert.equal(buffer.readUInt32LE(offset), 0x02014b50);
      assert.equal(buffer.readUInt16LE(offset + 10), 0);
      const length = buffer.readUInt16LE(offset + 28);
      const name = buffer.subarray(offset + 46, offset + 46 + length).toString();
      const local = buffer.readUInt32LE(offset + 42);
      assert.equal(buffer.readUInt32LE(local), 0x04034b50);
      const start = local + 30 + buffer.readUInt16LE(local + 26) + buffer.readUInt16LE(local + 28);
      const data = buffer.subarray(start, start + buffer.readUInt32LE(offset + 24));
      assert.equal(buffer.readUInt32LE(local + 14), buffer.readUInt32LE(offset + 16));
      assert.equal(buffer.readUInt32LE(offset + 16), referenceCrc32(data));
      assert.equal(buffer.readUInt16LE(local + 6), 0x800);
      files.set(name, data);
      offset += 46 + length + buffer.readUInt16LE(offset + 30) + buffer.readUInt16LE(offset + 32);
    }
    return files;
  }

  test("stored ZIP preserves Unicode names, binary bytes, CRC and central offsets", async () => {
    const { crc32 } = await import("node:zlib");
    assert.equal(zip.crc32(new TextEncoder().encode("123456789")), 0xcbf43926);
    const entries = [{ name: "assets/你好.png", data: new Uint8Array([0, 128, 255, 13, 10]) },
      { name: "empty.txt", data: "" }, { name: "README.md", data: "Hello π" }];
    const bytes = zip.createZip(entries);
    const result = unzip(bytes);
    for (const entry of entries) {
      const expected = typeof entry.data === "string" ? Buffer.from(entry.data) : Buffer.from(entry.data);
      assert.deepEqual(result.get(entry.name), expected);
      assert.equal(zip.crc32(expected), crc32(expected));
    }
    assert.equal(unzip(zip.createZip([])).size, 0);
  });

  test("ZIP refuses traversal, absolute paths, duplicate names and Windows aliases", () => {
    for (const name of ["../escape", "/absolute", "C:/escape", "a/../b", "a\\b", "a//b", "a/./b", "x\0y", "CON", "a/file.", "a/file "]) {
      assert.throws(() => zip.createZip([{ name, data: "x" }]), /path|name/i, name);
    }
    assert.throws(() => zip.createZip([{ name: "a", data: "1" }, { name: "A", data: "2" }]), /duplicate/i);
  });

  test("runtime snapshot matches the full current renderer, types, exporter and licenses", () => {
    for (const [name, source] of Object.entries(snapshot())) assert.ok(RUNTIME_SOURCE[name] === source,
      `${name} is stale. Run node --experimental-strip-types tools/studio/package-export.test.ts --sync-runtime`);
  });

  test("app/page/widget scope is isolated, positions normalized and omitted targets disclosed", () => {
    const input = project();
    assert.equal(pkg.scopeProject(input, { scope: "app" }).project.pages.length, 2);
    const page = pkg.scopeProject(input, { scope: "page", currentPageId: "first" });
    assert.equal(page.project.pages.length, 1);
    assert.match(page.warnings.join(" "), /second/);
    assert.doesNotThrow(() => parseProject(JSON.stringify(page.project)), "Scoped JSON must reopen without dangling targets");
    const widget = pkg.scopeProject(input, { scope: "widget", currentPageId: "first", widgetId: "next" });
    assert.equal(widget.project.pages[0]!.document.widgets[0]!.x, 0);
    assert.equal(widget.project.pages[0]!.document.widgets[0]!.y, 0);
    assert.doesNotThrow(() => parseProject(JSON.stringify(widget.project)), "Widget JSON must reopen without dangling targets");
    assert.equal(input.pages[0]!.document.widgets[0]!.id, "next");
    assert.throws(() => pkg.scopeProject(input, { scope: "widget", currentPageId: "first", widgetId: "absent" }));
    assert.throws(() => pkg.scopeProject(input, { scope: "page", currentPageId: "absent" }));
  });

  test("empty and whitespace page/widget names still export reimportable scoped projects", () => {
    for (const name of ["", "   "]) {
      const input = project();
      input.pages[0]!.document.name = name;
      input.pages[0]!.document.widgets[0]!.name = name;
      for (const scope of ["page", "widget"] as const) {
        const result = pkg.scopeProject(input, { scope, currentPageId: "first", widgetId: "next" });
        const reopened = parseProject(JSON.stringify(result.project));
        assert.ok(reopened.name.trim());
        assert.equal(reopened.pages[0]!.document.name, name);
        assert.equal(input.pages[0]!.document.widgets[0]!.name, name);
      }
    }
  });

  test("scoped ZIP README retains warnings while JSON removes omitted page links", () => {
    for (const scope of ["page", "widget"] as const) {
      const result = pkg.createReactPackage(project(), { scope, currentPageId: "first", widgetId: "next" });
      const files = unzip(zip.createZip(result.entries));
      assert.match(files.get("README.md")!.toString(), /Unavailable target "second"/);
      const reopened = parseProject(files.get("src/project.json")!.toString());
      assert.equal(reopened.pages.length, 1);
      assert.deepEqual(reopened.pages[0]!.document.widgets[0]!.actions, {});
    }
  });

  test("raster assets become deduplicated binary files and remote assets are disclosed", () => {
    const input = project();
    const data = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=";
    input.pages[0]!.document.widgets[0]!.content.image = data;
    input.pages[1]!.document.widgets = [structuredClone(input.pages[0]!.document.widgets[0]!)];
    Object.assign(input.pages[0]!.document, { backdrop: { kind: "image", image: data } });
    Object.assign(input.pages[1]!.document, { backdrop: { kind: "image", image: "https://example.com/remote.png" } });
    const result = pkg.createReactPackage(input);
    const assets = result.entries.filter((entry) => entry.name.startsWith("public/assets/"));
    assert.equal(assets.length, 1);
    assert.deepEqual(Buffer.from(assets[0]!.data), Buffer.from(data.split(",")[1]!, "base64"));
    const json = String(result.entries.find((entry) => entry.name === "src/project.json")!.data);
    assert.ok(!json.includes("data:image"));
    assert.match(json, /assets\/image-1.png/);
    assert.match(result.warnings.join(" "), /https:\/\/example.com\/remote.png/);
    assert.equal(input.pages[0]!.document.widgets[0]!.content.image, data);
    input.pages[0]!.document.widgets[0]!.content.image = "data:image/svg+xml;base64,PHN2Zz4=";
    assert.throws(() => pkg.createReactPackage(input), /raster|image/i);
  });

  test("standalone project navigation changes pages with fixed code and safe serialized content", () => {
    const input = project();
    input.name = '</script><script>globalThis.pwned=true</script>';
    input.pages[0]!.document.widgets[0]!.content.title = input.name;
    const html = exporter.exportProjectHtml(input, "second");
    assert.ok(!html.includes('<script>globalThis.pwned'));
    assert.match(html, /Second page/);
    const payload = html.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!;
    const script = html.match(/<script>([\s\S]*?)<\/script>/i)![1]!;
    const listeners: Record<string, (event: unknown) => void> = {};
    const host = { innerHTML: "", querySelectorAll: () => [], querySelector: () => null,
      addEventListener: (type: string, handler: (event: unknown) => void) => { listeners[type] = handler; } };
    const window: { parent?: unknown } = {};
    window.parent = window;
    const doc = { title: "", addEventListener() {}, getElementById: (id: string) => id === "nimbus-data" ? { textContent: payload } : host };
    runInNewContext(script, { document: doc, window });
    assert.match(host.innerHTML, /Second page/);
    const firstHtml = exporter.exportProjectHtml(input, "first");
    const firstPayload = firstHtml.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!;
    runInNewContext(script, { window, document: { ...doc, getElementById: (id: string) => id === "nimbus-data" ? { textContent: firstPayload } : host } });
    const node = { getAttribute: () => "next" };
    const target = { closest: (selector: string) => selector === "[data-id]" ? node : null };
    listeners["click"]!({ target, preventDefault() {} });
    assert.match(host.innerHTML, /Second page/);
    assert.ok(exporter.exportHtml(input.pages[0]!.document).includes("&lt;script&gt;"));
  });

  test("iframe protocol reports initial/navigation page and Escape, while item targets cannot leave the export", () => {
    const input = project();
    const html = exporter.exportProjectHtml(input, "first");
    const payload = html.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!;
    const script = html.match(/<script>([\s\S]*?)<\/script>/i)![1]!;
    const listeners: Record<string, (event: unknown) => void> = {};
    const documentListeners: Record<string, (event: unknown) => void> = {};
    const messages: unknown[] = [];
    const host = { innerHTML: "", querySelectorAll: () => [], querySelector: () => null,
      addEventListener: (type: string, handler: (event: unknown) => void) => { listeners[type] = handler; } };
    runInNewContext(script, { window: { parent: { postMessage: (message: unknown, origin: string) => { assert.equal(origin, "*"); messages.push(JSON.parse(JSON.stringify(message))); } } },
      document: { title: "", getElementById: (id: string) => id === "nimbus-data" ? { textContent: payload } : host,
        addEventListener: (type: string, handler: (event: unknown) => void) => { documentListeners[type] = handler; } } });
    assert.deepEqual(messages, [{ type: "nimbus:page", pageId: "first" }]);
    const node = { getAttribute: () => "next" };
    let destination = "https://evil.example";
    const item = { getAttribute: () => destination, classList: { contains: () => false } };
    const target = { closest: (selector: string) => selector === "[data-id]" ? node : selector === "[data-nimbus-page]" ? item : null };
    listeners["click"]!({ target, preventDefault() {} });
    assert.equal(messages.length, 1);
    destination = "second";
    listeners["click"]!({ target, preventDefault() {} });
    assert.deepEqual(messages[1], { type: "nimbus:page", pageId: "second" });
    documentListeners["keydown"]!({ key: "Escape" });
    assert.deepEqual(messages[2], { type: "nimbus:close-preview" });
  });

  test("whole-widget links do not hijack input clicks or typed spaces", () => {
    const input = project();
    const html = exporter.exportProjectHtml(input);
    const payload = html.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!;
    const script = html.match(/<script>([\s\S]*?)<\/script>/i)![1]!;
    const listeners: Record<string, (event: unknown) => void> = {};
    const host = { innerHTML: "", querySelectorAll: () => [], querySelector: () => null,
      addEventListener: (type: string, handler: (event: unknown) => void) => { listeners[type] = handler; } };
    const window: { parent?: unknown } = {}; window.parent = window;
    runInNewContext(script, { window, document: { title: "", addEventListener() {},
      getElementById: (id: string) => id === "nimbus-data" ? { textContent: payload } : host } });
    const node = { getAttribute: () => "next" };
    const surface = { getAttribute: () => "second", classList: { contains: (name: string) => name === "nw-surface" } };
    const target = { closest: (selector: string): unknown => selector === "[data-id]" ? node : selector === "[data-nimbus-page]" ? surface : selector.startsWith("input,") ? target : null };
    for (const type of ["click", "keydown"]) listeners[type]!({ type, key: " ", target, preventDefault() {} });
    assert.ok(!host.innerHTML.includes("Second page"));
  });

  let compiledRuntime: Promise<string> | undefined;
  async function runPackagedRuntime(input: ReturnType<typeof project>, href: string) {
    const archive = pkg.createReactPackage(input);
    const appRequire = createRequire(join(root, "apps/reference-vite/package.json"));
    compiledRuntime ??= (async () => {
      const sources = new Map(archive.entries.filter((entry) => entry.name.startsWith("packages/runtime/src/"))
        .map((entry) => ["\0nimbus/" + entry.name.slice("packages/runtime/src/".length), String(entry.data)]));
      const { build } = await import(pathToFileURL(appRequire.resolve("vite")).href);
      const result = await build({
        configFile: false, root, logLevel: "silent",
        plugins: [{ name: "extracted-nimbus-runtime",
          resolveId(id: string, importer?: string) {
            if (id.endsWith("virtual:nimbus-runtime")) return "\0nimbus/index.tsx";
            if (!id.startsWith(".") || !importer?.startsWith("\0nimbus/")) return undefined;
            const path = posix.normalize(posix.join(posix.dirname(importer), id));
            return [path, path + ".ts", path + ".tsx"].find((name) => sources.has(name));
          },
          load(id: string) { return sources.get(id); },
        }],
        build: { write: false, minify: false, lib: { entry: "virtual:nimbus-runtime", formats: ["cjs"] },
          rolldownOptions: { external: ["react", "react/jsx-runtime"] } },
      });
      const bundle = Array.isArray(result) ? result[0] : result;
      return bundle.output.find((item: { type: string }) => item.type === "chunk")!.code;
    })();
    let html = "";
    // Only React's hook scheduling is replaced in this non-DOM harness. The emitted
    // component, asset adapter, shared renderer and fixed script all execute unchanged.
    const react = appRequire("react");
    const require = (name: string) => name === "react" ? { ...react,
      useEffect: (effect: () => void) => effect(),
      useState: () => ["", (value: string) => { html = value; }],
    } : appRequire(name);
    const module = { exports: {} as { NimbusPrototype?: (props: unknown) => unknown } };
    runInNewContext(await compiledRuntime, { require, module, exports: module.exports, URL,
      window: { location: { href } } });
    module.exports.NimbusPrototype!({ project: archive.project });
    assert.ok(html, "The runtime effect must publish an iframe document");
    return html;
  }

  test("packaged backgrounds preserve CSS URL escaping beneath parenthesized deployment paths", async () => {
    const input = project();
    const backdrop = { type: "image" as const,
      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=",
      size: "cover" as const, positionX: 50, positionY: 50, repeat: "no-repeat" as const };
    input.pages[0]!.document.backdrop = backdrop;
    input.pages[0]!.document.widgets[0]!.style.backdrop = backdrop;
    const html = await runPackagedRuntime(input, "https://example.test/previews/(demo)/");
    const payload = JSON.parse(html.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!);
    const pageHtml = payload.pages[0].html as string;
    assert.ok(pageHtml.includes("background-image:url(https://example.test/previews/%28demo%29/assets/image-1.png)"));
    assert.ok(!pageHtml.includes("url(https://example.test/previews/(demo)/"));
    assert.equal(pageHtml.match(/background-image:url\(/g)?.length, 2);
  });

  test("packaged runtime resolves image fields without rewriting authored text resembling asset paths", async () => {
    const input = project();
    input.name = "assets/image-1.png";
    const document = input.pages[0]!.document;
    document.name = "assets/image-1.png";
    const widget = document.widgets[0]!;
    widget.kind = "image";
    widget.content.title = "assets/image-1.png";
    widget.content.subtitle = "assets/image-2.png";
    widget.content.imageAlt = "assets/image-1.png";
    widget.content.image = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=";
    const html = await runPackagedRuntime(input, "https://example.test/previews/demo/");
    assert.ok(html.includes("<title>assets/image-1.png</title>"));
    const payload = JSON.parse(html.match(/<script id="nimbus-data" type="application\/json">([\s\S]*?)<\/script>/)![1]!);
    assert.equal(payload.pages[0].name, "assets/image-1.png");
    assert.match(payload.pages[0].html, /alt="assets\/image-1.png"/);
    assert.match(payload.pages[0].html, /<strong>assets\/image-1.png<\/strong>/);
    assert.match(payload.pages[0].html, /assets\/image-2.png<\/small>/);
    assert.match(payload.pages[0].html, /src="https:\/\/example.test\/previews\/demo\/assets\/image-1.png"/);
  });

  test("extracted React ZIP builds as a standalone Vite consumer and includes full source/licenses", async () => {
    const input = project();
    input.pages[0]!.document.widgets = widgetCatalog.map((definition) => createWidget(definition));
    const image = input.pages[0]!.document.widgets.find((widget) => widget.kind === "image")!;
    image.content.image = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=";
    const sidebar = input.pages[0]!.document.widgets.find((widget) => widget.kind === "sidebar")!;
    sidebar.actions = { "item:0": "second" };
    const result = pkg.createReactPackage(input);
    const files = unzip(zip.createZip(result.entries));
    assert.ok(files.get("packages/runtime/src/render.ts")!.toString() === canonicalSourceText(readFileSync(join(studio, "render.ts"), "utf8")), "ZIP renderer must match current source; run source sync");
    assert.equal(files.get("packages/runtime/LICENSE")!.toString(), canonicalSourceText(readFileSync(join(root, "LICENSE"), "utf8")));
    assert.equal(files.get("THIRD_PARTY_NOTICES.md")!.toString(), canonicalSourceText(readFileSync(join(root, "THIRD_PARTY_NOTICES.md"), "utf8")));
    const dir = mkdtempSync(join(tmpdir(), "nimbus-export-consumer-"));
    for (const [name, data] of files) {
      mkdirSync(dirname(join(dir, name)), { recursive: true });
      writeFileSync(join(dir, name), data);
    }
    // Link only installed third-party dependencies, never Nimbus workspace source.
    const appRequire = createRequire(join(root, "apps/reference-vite/package.json"));
    const rootRequire = createRequire(join(root, "package.json"));
    for (const name of ["react", "react-dom", "vite", "@types/react", "@types/react-dom", "typescript"]) {
      const resolve = name === "typescript" ? rootRequire : appRequire;
      const packageDir = dirname(resolve.resolve(name + "/package.json"));
      const destination = join(dir, "node_modules", name);
      mkdirSync(dirname(destination), { recursive: true });
      symlinkSync(packageDir, destination, "junction");
    }
    mkdirSync(join(dir, "node_modules/@nimbus-ui"), { recursive: true });
    symlinkSync(join(dir, "packages/runtime"), join(dir, "node_modules/@nimbus-ui/runtime"), "junction");
    try {
      execFileSync(process.execPath, [join(dirname(rootRequire.resolve("typescript/package.json")), "bin/tsc"), "--noEmit", "-p", join(dir, "tsconfig.json")], { cwd: dir, stdio: "pipe" });
    } catch (error) {
      throw new Error(String((error as { stdout?: Buffer }).stdout ?? error));
    }
    const { build } = await import(pathToFileURL(appRequire.resolve("vite")).href);
    await build({ root: dir, configFile: join(dir, "vite.config.ts"), logLevel: "silent" });
    assert.ok(readFileSync(join(dir, "dist/index.html"), "utf8").includes("assets/"));
    assert.deepEqual(readFileSync(join(dir, "dist/assets/image-1.png")), Buffer.from(image.content.image.split(",")[1]!, "base64"));
    process.stdout.write("Consumer fixture: " + dir + "\n");
  });
}
