async (page) => {
  const assert=(ok,message)=>{if(!ok)throw new Error(message);};
  const blank=async()=>{await page.locator('.studio-project-button').click();await page.getByRole('button',{name:'New blank page',exact:true}).click();};
  await blank();
  await page.getByRole('button',{name:'Add Card',exact:true}).click();
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await page.evaluate(()=>{const native=FileReader.prototype.readAsDataURL;FileReader.prototype.readAsDataURL=function(file){setTimeout(()=>native.call(this,file),800);};});
  await page.getByLabel('Upload widget image',{exact:true}).setInputFiles('output/playwright/nimbus-studio-desktop.png');
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Newer title survives upload');
  await page.locator('.studio-upload-preview').waitFor();
  assert((await page.locator('.studio-canvas-widget').first().innerText()).includes('Newer title survives upload'),'Upload overwrote intervening text');
  await page.getByRole('textbox',{name:'Layer name',exact:true}).fill('a'.repeat(120));
  await page.getByRole('button',{name:'Duplicate selected widget',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.studio-save-state')?.textContent==='Saved locally');
  await page.reload();
  await page.waitForFunction(()=>document.querySelectorAll('.studio-canvas-widget').length===2);
  assert(await page.locator('.studio-canvas-widget').count()===2,'Maximum layer name failed after duplication and reload');
  await page.locator('.studio-canvas-widget').last().click();
  await page.getByRole('button',{name:'Export code',exact:true}).click();
  await page.getByRole('button',{name:'Nimbus project',exact:true}).click();
  await page.getByRole('button',{name:'Selected widget only',exact:true}).click();
  const one=JSON.parse(await page.getByRole('textbox',{name:'Generated code',exact:true}).inputValue());
  assert(one.widgets.length===1 && one.widgets[0].x===0,'Selected-widget export failed');
  await page.getByRole('button',{name:'Whole page',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download',exact:true}).click();
  const download=await downloadPromise;await download.saveAs('output/playwright/nimbus-roundtrip.json');
  await page.getByRole('button',{name:'Close export',exact:true}).click();
  await blank();
  await page.getByLabel('Import Nimbus project',{exact:true}).setInputFiles('output/playwright/nimbus-roundtrip.json');
  await page.waitForFunction(()=>document.querySelectorAll('.studio-canvas-widget').length===2);
  assert((await page.locator('.studio-canvas-widget').first().innerText()).includes('Newer title survives upload'),'Import lost content');
  await page.evaluate(()=>localStorage.setItem('nimbus.visual-studio.v1','{"version":999}'));
  await page.reload();
  await page.waitForFunction(()=>document.querySelector('.studio-save-state')?.textContent==='Recovery needed');
  await page.locator('.studio-canvas-widget').nth(3).click();
  await page.waitForTimeout(800);
  assert(await page.evaluate(()=>localStorage.getItem('nimbus.visual-studio.v1'))==='{"version":999}','Selection overwrote recovery data');
  await blank();
  await page.getByRole('button',{name:'Add Image',exact:true}).click();
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await page.evaluate(()=>{const native=FileReader.prototype.readAsDataURL;FileReader.prototype.readAsDataURL=function(file){setTimeout(()=>native.call(this,file),800);};});
  await page.getByLabel('Upload widget image',{exact:true}).setInputFiles('output/playwright/nimbus-studio-desktop.png');
  await blank();await page.waitForTimeout(1200);
  assert(await page.locator('.studio-canvas-widget').count()===0,'Obsolete upload resurrected replaced page');
  console.log('PASS: delayed upload preservation, max-name duplicate/reload, selected export, downloaded JSON import, recovery selection, obsolete upload cancellation.');
}
