async (page) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  const check=(ok,message)=>{if(!ok)throw new Error(message);};
  const button=name=>page.getByRole('button',{name,exact:true});
  await page.getByRole('button',{name:'Preview',exact:true}).waitFor();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await button('17 templates').click();
  await page.getByRole('dialog').waitFor();
  check(await page.locator('.studio-template-card').count()===17,'17 gallery compositions missing');
  await page.getByRole('searchbox',{name:'Find a template'}).fill('CRM');
  check(await page.locator('.studio-template-card').count()===1,'Gallery search failed');
  await button('CRM pipeline').click();
  const crmId=await page.getByRole('combobox',{name:'Current page',exact:true}).inputValue();
  check(await page.locator('.studio-canvas-widget').count()>=7,'Template not populated');
  await button('Manage pages').click();
  await button('Add blank page').click();
  await page.getByRole('textbox',{name:'Page name',exact:true}).fill('Prototype home');
  const homeId=await page.getByRole('combobox',{name:'Current page',exact:true}).inputValue();
  await page.getByRole('combobox',{name:'Background type',exact:true}).selectOption('linear');
  check((await page.locator('.studio-page').evaluate(el=>getComputedStyle(el).backgroundImage)).startsWith('linear-gradient('),'Page gradient missing');
  await button('Text').click();
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Go to CRM');
  await page.getByRole('combobox',{name:'Whole widget target',exact:true}).selectOption(crmId);
  check((await page.locator('.studio-canvas-widget').innerText()).includes('Go to CRM'),'New text content not edited');
  await page.getByRole('tab',{name:'Motion',exact:true}).click();
  await page.getByRole('combobox',{name:'On load',exact:true}).selectOption('slide');
  await page.getByRole('combobox',{name:'Easing',exact:true}).selectOption('ease-in-out');
  await page.getByRole('combobox',{name:'Loading appearance',exact:true}).selectOption('spinner');
  await page.getByRole('combobox',{name:'Preview state',exact:true}).selectOption('loading');
  check(await page.locator('.studio-canvas-widget .nw-spinner').count()===1,'Loading spinner missing');
  await page.getByRole('combobox',{name:'Preview state',exact:true}).selectOption('default');
  await button('Preview').click();
  const frame=page.frameLocator('iframe[title="Full-screen interactive prototype"]');
  await frame.getByText('Go to CRM',{exact:true}).waitFor();
  const size=await page.locator('.studio-prototype').boundingBox();
  check(size.width===1600&&size.height===1000,'Preview does not fill viewport');
  await frame.getByText('Go to CRM',{exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('select[aria-label="Preview page"]')?.value===id,crmId);
  const input=frame.locator('input').first();
  await input.fill('Retain this while resizing');
  await button('Mobile').click();
  check(await page.getByRole('combobox',{name:'Preview page',exact:true}).inputValue()===crmId,'Device switch lost navigation');
  check(await input.inputValue()==='Retain this while resizing','Device switch reset form state');
  await button('Full width').click();
  await button('Fullscreen').click();
  await page.waitForFunction(()=>document.fullscreenElement?.classList.contains('studio-prototype-shell'));
  await button('Fullscreen').click();
  await page.waitForFunction(()=>!document.fullscreenElement);
  await page.screenshot({path:'output/playwright/nimbus-v2-full-preview.png',fullPage:true});
  await button('Back to editor').click();
  check(await button('Preview').evaluate(el=>el===document.activeElement),'Preview focus not restored');
  await page.getByRole('tab',{name:'Design',exact:true}).click();
  await page.getByRole('combobox',{name:'Background type',exact:true}).selectOption('image');
  await page.getByLabel('Upload background image',{exact:true}).setInputFiles('output/playwright/nimbus-studio-desktop.png');
  await page.locator('.studio-upload-preview').waitFor();
  const background=await page.locator('.studio-widget-render .nw-node').evaluate(el=>getComputedStyle(el).backgroundImage);
  check(background.includes('data:image/png;base64,'),'Uploaded background is broken');
  await page.getByRole('tab',{name:'Design',exact:true}).click();
  await page.locator('.vp-disclosure').first().locator('summary').click();
  await page.getByRole('spinbutton',{name:'title size (px)',exact:true}).fill('32');
  await page.getByRole('spinbutton',{name:'title size (px)',exact:true}).press('Tab');
  check(await page.locator('.studio-widget-render [data-nw-text="title"]').evaluate(el=>getComputedStyle(el).fontSize)==='32px','Granular title size ignored');
  await button('Export code').click();
  const code=page.getByRole('textbox',{name:'Generated code',exact:true});
  check((await code.inputValue()).includes('@nimbus-ui/runtime'),'React component missing Nimbus package import');
  await button('Standalone HTML').click();
  check((await code.inputValue()).includes('data:image/png;base64,'),'HTML missing uploaded asset');
  await button('Selected widget only').click();
  check((await code.inputValue()).includes('Go to CRM'),'Selected export missing widget');
  check(await page.getByLabel('Export notices').count()===1,'Scoped export does not explain missing destination');
  await button('Whole app').click();
  const download=page.waitForEvent('download');
  await button('Download React ZIP').click();
  await (await download).saveAs('output/playwright/nimbus-v2-react-project.zip');
  await button('Nimbus project').click();
  const exported=JSON.parse(await code.inputValue());
  check(exported.version===2&&exported.pages.length>=3,'Multi-page project missing');
  check(exported.pages.find(p=>p.id===homeId).document.widgets[0].actions.click===crmId,'Page link not exported');
  await button('Close export').click();
  await page.waitForFunction(()=>document.querySelector('.studio-save-state')?.textContent==='Saved locally');
  await page.reload();
  await page.getByRole('combobox',{name:'Current page',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Current page',exact:true}).selectOption(homeId);
  check((await page.locator('.studio-canvas-widget').innerText()).includes('Go to CRM'),'Database reload lost content');
  await page.getByRole('combobox',{name:'Current page',exact:true}).selectOption(crmId);
  await page.locator('.studio-canvas-widget').first().click();
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await page.getByLabel('Upload sidebar logo',{exact:true}).setInputFiles('output/playwright/nimbus-studio-desktop.png');
  await page.locator('.studio-upload-preview').waitFor();
  await page.getByRole('spinbutton',{name:'Logo width (px)',exact:true}).fill('80');
  await page.getByRole('spinbutton',{name:'Logo width (px)',exact:true}).press('Tab');
  check(await page.locator('.studio-widget-render .nw-logo').evaluate(el=>getComputedStyle(el).width)==='80px','Sidebar logo size ignored');
  await page.getByRole('textbox',{name:'Navigation 1 label',exact:true}).fill('Home');
  await page.getByRole('textbox',{name:'Navigation 1 label',exact:true}).press('Tab');
  await page.getByRole('combobox',{name:'Navigation 1 target',exact:true}).selectOption(homeId);
  await button('Preview').click();
  await frame.getByRole('button',{name:'Home',exact:true}).click();
  await frame.getByText('Go to CRM',{exact:true}).waitFor();
  await frame.locator('main').press('Escape');
  await button('Preview').waitFor();
  await page.screenshot({path:'output/playwright/nimbus-v2-editor.png',fullPage:true});
  check(errors.length===0,`Browser errors: ${errors.join('; ')}`);
  console.log('PASS: 17-template gallery, page creation, gradient, text, motion/loading, navigation, device continuity, native fullscreen, focus restoration, upload/typography, scoped HTML/React ZIP, IndexedDB reload and editable linked sidebar logo.');
}
